### ISSUE TITLE
Multiple Values - could there be multiple selections?

### ISSUE THREAD

**Issue by daviddelmonte** [futuretap/InAppSettingsKit#107]
I have a preference setting where I'd like users to be able to make multiple choices within a  Multiple Value setting. Is that possible? (For example, select "Tea", "Milk", and "Sugar")

If not, I'll have to turn the multiple choices into individual choices, but I'd prefer not to do that.

Thanks

**Comment by futuretap** [comment]
See the sample app under List Groups > Show Accounts > Add Account > Roles. Hope that does what you're looking for. We're using `IASKToggleStyle: Checkmark` here.
