### ISSUE TITLE
customizable footers?

### ISSUE THREAD

**Issue by diederich** [futuretap/InAppSettingsKit#118]
While the headers of the settings tableview can be easily customized,  there seems to be no way to customize the footers.

I've created a branch (based on the settings cleanup IASKSettingsDelegate-changes branch) which tries to mimic the style of header customization:
https://github.com/diederich/InAppSettingsKit/tree/features/customizable-footers

Let me know if this needs changes...

**Comment by wkoszek** [comment]
@diederich it'd be nice to have. I use a custom footer to show build version on the very bottom of the settings screen. Would you be interested in generating the pull request for this?

**Comment by futuretap** [comment]
Should be included already.
