### ISSUE TITLE
customize the UI without subclassing

### ISSUE THREAD

**Issue by JanC** [futuretap/InAppSettingsKit#178]
Hi,
this is related to #174

The idea is to be able to customize that uitables and ui cells without having to subclass the IASKAppSettingsViewController.

I know there is the -[IASKSettingsDelegate tableView:cellForSpecifier:] but this forces the user to create an entire cell. I just want to offer the possibility to change the text font, color, background color and so on.

A proposal could be to have another delegate that is responsible just for theming of the created cells. E.g.:

```
@protocol IASKSettingsThemeDelegate
@optional
- (void) settingsViewController:(id<IASKViewController>)settingsViewController themeTableView:(UITableView*)tableView;
- (void) settingsViewController:(id<IASKViewController>)settingsViewController tableView:(UITableView*)tableView themeCell:(UITableViewCell*)cell;
@end
```

The user could then use it:

```
#pragma mark - IASKSettingsThemeDelegate
- (void)settingsViewController:(id <IASKViewController>)settingsViewController tableView:(UITableView *)tableView themeCell:(UITableViewCell *)cell {
    [ThemeManager customizeTableCell: cell inTableView:tableView];
}


- (void)settingsViewController:(id <IASKViewController>)settingsViewController themeTableView:(UITableView *)tableView {
    [ThemeManager customizeTableView: tableView];
}
```

**Comment by zboralski** [comment]
@futuretap what about multi value's cell?
