### ISSUE TITLE
settingsViewControllerDidEnd not called

### ISSUE THREAD

**Issue by yangnw** [futuretap/InAppSettingsKit#206]
I have a navigation controller with master controller pushing to settings controller, etc

``` objective-c
@interface ReferencesController : UITableViewController <IASKSettingsDelegate>
- (void)settingsViewControllerDidEnd:(IASKAppSettingsViewController *)sender { NSLog(@"ending"); }
```

And it's not called. A have to use a model push and implement my own back button. Could this be implemented so that backing from navigation controller calls the delegate method?

**Comment by futuretap** [comment]
Please check if the issue persists in the latest update and create a new issue if needed.
