### ISSUE TITLE
Allow use of custom Localization class

### ISSUE THREAD

**Issue by hongkongkiwi** [futuretap/InAppSettingsKit#221]
Currently almost all the localization is done inside:

`- (NSString*)titleForStringId:(NSString*)stringId`

It makes sense however to allow this to be extended so that people can use their own custom localizer class. I suggest to add a "Localization" class which responds to the method titleForStringId.

e.g.

``` objective-c
- (NSString*)titleForStringId:(NSString*)stringId {
    if (self.customLocalizer && [customLocalizer respondsToSelector:@selector(stringWithKey:)]) {
        return [self.customLocalizer stringWithKey:stringId];
    } else {
        return [self.settingsBundle localizedStringForKey:stringId value:stringId table:self.localizationTable];
    }
}
```

**Comment by futuretap** [comment]
You can specify a `StringsTable` in the plist to define your own Localizable.strings file. See https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/UserDefaults/Preferences/Preferences.html
