### ISSUE TITLE
Register Defaults from Settings Plist

### ISSUE THREAD

**Issue by malhal** [futuretap/InAppSettingsKit#244]
It would be nice if it used the default values in the settings plist to registerDefaults with. Would save a lot of code. The other in-app settings achieves it like this:

@implementation AppDelegate

//intialise defaults from default value keys in Root.plist.
- (void)initialize{
  if([self class] == [AppDelegate class]){
      [InAppSettings registerDefaults];
  }
  }

https://github.com/kgn/InAppSettings

**Comment by malhal** [comment]
Since I opened this issue a long time ago I've actually been using the other InAppSettings project that does this via it's [InAppSettingsReaderRegisterDefaults](https://github.com/kgn/InAppSettings/blob/master/InAppSettings/InAppSettingsReader.m) class fully automatically.

**Comment by futuretap** [comment]
IASK 3.0 addresses this with a new [gatherDefaults](https://github.com/futuretap/InAppSettingsKit#register-default-values) method.
