### ISSUE TITLE
MainWindow.xib missing?

### ISSUE THREAD

**Issue by rlaferla** [futuretap/InAppSettingsKit#245]
InAppSettingsKit/InAppSettingsKitSampleApp/en.lproj/MainWindow.xib: Interface Builder could not open the document "MainWindow.xib" because it does not exist.

**Comment by BrainyMonkeyTuts** [comment]
if you copied some files from another app to yours,you will get this error..click on the error,then in the information window in Xcode it will show you the location of the missing file..replace that file from your recycling bin.You might have deleted it by mistake.Then if you don't need that file for your app,simply remove references to that file then clean and build your app.
