### ISSUE TITLE
Height Adjustment for IASKAppSettingsViewController in Popover

### ISSUE THREAD

**Issue by semireg** [futuretap/InAppSettingsKit#248]
I'm modifying the headers of the IASKAppSettingsViewController using the following delegate methods.  However, the height of the final table is larger than the cells it now occupies.  What is the best way to recalculate the table's content size?  I've tried invalidating... manually setting contentSize but have not gotten the expected results.

```
- (CGFloat) settingsViewController:(id<IASKViewController>)settingsViewController
                         tableView:(UITableView *)tableView
         heightForHeaderForSection:(NSInteger)section
{
    if(section == 0)
        return 44;
    else
        return 0;
}

- (UIView *) settingsViewController:(id<IASKViewController>)settingsViewController
                          tableView:(UITableView *)tableView
            viewForHeaderForSection:(NSInteger)section
{
    if(section == 0)
        return nil;
    else
        return [[UIView alloc] init];
}
```

**Comment by futuretap** [comment]
Please check if the issue persists in the latest update and create a new issue if needed.
