### ISSUE TITLE
Sample does not work & Auto Layout

### ISSUE THREAD

**Issue by feb1234** [futuretap/InAppSettingsKit#256]
Hi Guys,

I download the zip package from Github. Unzip it, then using Xcode 5 open the sameple project file called InAppSettingsKitSampleApp.xcodeproj under folder inAppSettingsKitSampleApp.

Run, then got error "Interface Buikder could not open the document "MainWindow.xib" because it doe not exist."

From the project, the full path of MainWindow.xib is pointing to the root of  inAppSettingsKitSampleApp. But in Finder, the MainWindow.xib is under inAppSettingsKitSampleApp\Base.lproj.

Try to fix it by myself. Delete MainWindow.xib from project, then Add it from Base.lproj. Then add Localizations.

Run, no error so far. But click Setting tab, click "Update at launch    Maybe>" cell, it gave error like "In App Settings Ket  [UITableView tintColor]: unrecognized selector sent to instance xxxxxx Terminating app due to uncaught exception 'NSInvalidArgumentException', ............ libc++abi.dylib: terminate called throwing an exception."

Would you please try to run the sample at a new environment (new user) to duplicate and fix the issue?

Thanks.

**Comment by futuretap** [comment]
Does this issue still exist in the newest version? Closing it for now. Please create new, separate issues if it still occurs.
