### ISSUE TITLE
Wrong Indexpath returned

### ISSUE THREAD

**Issue by chinabshah** [futuretap/InAppSettingsKit#257]
When having multiple identifers in the tableview. First 3 are textfield and last to are buttons. When the keyboard is displayed and when the last button is pressed then the indexpath returns second last cell indexpath.

This does not happen if the keyboard is not displayed. Also the there are group identifiers also being used to separate the textfield settings from the button settings.

**Comment by futuretap** [comment]
Please check if the issue persists in the latest update and create a new issue if needed.
