### ISSUE TITLE
iOS 8: Keyboard dismiss late

### ISSUE THREAD

**Issue by neilyoung** [futuretap/InAppSettingsKit#269]
I have noticed, that on iOS8 the keyboard dismisses later than the viewcontroller disappears from screen (roughly one second later). This makes the UI appear sluggish.

To prevent this I have changed the dismiss method in my private copy of InAppSettingsViewController to

	- (void)dismiss:(id)sender {
		[self.settingsStore synchronize];
		[self.currentFirstResponder resignFirstResponder];
		if (self.delegate && [self.delegate conformsToProtocol:@protocol(IASKSettingsDelegate)]) {
			[self.delegate settingsViewControllerDidEnd:self];
		}
	}

HTH

**Comment by futuretap** [comment]
Closing for now. Please reopen with a sample app should you still experience the issue.
