### ISSUE TITLE
Improvement for MainStoryBoard when using older Universal apps that have 2 Storyboard files

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#278]
My app is created with Xcode 5, where a universal app was created by default with 2 storyboard files: 1 for iPhone and 1 for iPad. They are called:
- Main_iPhone.storyboard
- Main_iPad.storyboard

When using IASKViewControllerStoryBoardId to load a view from Storyboard, the app crashes with:
```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'MainStoryboard' in bundle NSBundle
```
Since there is not a single storyboard file in my project, I can't use IASKViewControllerStoryBoardFile.

I have pinpointed the issue to the next section of 'tableView didSelectRowAtIndexPath:' in IASKAppSettingsViewController.m:
```
if ([specifier viewControllerStoryBoardID]){
            NSString *storyBoardFileFromSpecifier = [specifier viewControllerStoryBoardFile];
            storyBoardFileFromSpecifier = storyBoardFileFromSpecifier && storyBoardFileFromSpecifier.length > 0 ? storyBoardFileFromSpecifier : @"MainStoryboard";
			UIStoryboard *storyBoard = [UIStoryboard storyboardWithName:storyBoardFileFromSpecifier bundle:nil];
			UIViewController * vc = [storyBoard instantiateViewControllerWithIdentifier:[specifier viewControllerStoryBoardID]];
			IASK_IF_IOS7_OR_GREATER(vc.view.tintColor = self.view.tintColor;)
            [self.navigationController pushViewController:vc animated:YES];
			return;
		}
```
To solve the issue, I have replaced the hardcoded string @"MainStoryboard" in the declaration of storyBoardFileFromSpecifier with dynamic value:
```
[[NSBundle mainBundle].infoDictionary objectForKey:@"UIMainStoryboardFile"]
```

This solves the issue.
Can you incorporate this in a next update?
Thank you.

**Comment by futuretap** [comment]
Can you create a pull request? Will be happy to accept it!

**Comment by funnel20** [comment]
Hi Ortwin,

I haven't a lot of experience with Github, so just checking.
Should I fork your master branch, edit the code and use my fork as comparison to your master when making the pull request?

With kind regards,

Martijn

**Comment by futuretap** [comment]
Hi Martijn, that's exactly how you should do it!

**Comment by funnel20** [comment]
Th pull request is ready for you.

**Comment by futuretap** [comment]
Thanks

**Comment by funnel20** [comment]
Verified
