### ISSUE TITLE
Populate a PSMultiValueSpecifier group at runtime

### ISSUE THREAD

**Issue by nmock** [futuretap/InAppSettingsKit#280]
Is it possible to dynamically generate / load generate the titles/values for a PSMultiValueSpecifier group at launch? I am defining some values from another plist and want to sync up the values. Is it possible to grab the IASKSpecifier, modify the values, and synchronize the preferences? What is the right approach to accomplishing something like this? 

In regards to the example, I am trying to accomplish something like the "multiple values (update at launch)" example, just with values supplied at runtime.

**Comment by futuretap** [comment]
This has been added in the 2.9 release today.
