### ISSUE TITLE
IOS6 bug in IASKSettingsViewController

### ISSUE THREAD

**Issue by mournblade** [futuretap/InAppSettingsKit#281]
Row 603.

if (specifier.textAlignment != NSTextAlignmentLeft) {
			cell.textLabel.textColor = tableView.tintColor;
		}

You have forgotten the respondstoselector since tintColor only available in IOS7 and forward. My app crashes.

**Comment by futuretap** [comment]
Already fixed in 42105f682f8cb633c0fd11ec355ebee9f7dd090e.

**Comment by mournblade** [comment]
Heh, that was quick, good stuff.
