### ISSUE TITLE
Problem with uinavigationbar and tabs in IOS6.

### ISSUE THREAD

**Issue by mournblade** [futuretap/InAppSettingsKit#282]
I'll try to explain, let me know if you need anything else.

I have a tabbed app. I have added uisettingskit to one of them (i'm trying it out). The tabs in my app are without names, i.e. only icons.

To avoid a root-header that says "Settings" in my tab, i have added
"Settings" = "";
to my localizable files. This works fine in IOS7/8, when i go into a submenu the navigation "back" button is a "<" as i would expect.

HOWEVER, this does not work in IOS6, since apparently it requires a name which it uses for the back button. If i have like above, the back button does not appear when i go into a sub menu, making the user stuck in the sub menu.

So i'm kind of stuck between a rock and a hard place. If i have a "Settings"-string, my tab gets a string added which i don't want, but if i remove it, i don't get a back button.

**Comment by futuretap** [comment]
This problem is a general iOS problem and not a specific IASK issue. I suggest asking on StackOverflow or the  DevForums.
