### ISSUE TITLE
iOS 8 `IASKTextAlignment ` seems not working

### ISSUE THREAD

**Issue by BoilingLime** [futuretap/InAppSettingsKit#283]
I'm trying to align center a button using `IASKUITextAlignmentCenter ` in plist file but it is not working. I notified that it is actually not working in the sample app you provide either. Do I miss something ?

**Comment by futuretap** [comment]
This was a regression and has been fixed in [2.4](https://github.com/futuretap/InAppSettingsKit/releases/tag/2.4). Thanks!
