### ISSUE TITLE
Selection Bug [re-open]

### ISSUE THREAD

**Issue by nmock** [futuretap/InAppSettingsKit#285]
@futuretap, not sure if you're able to open up the old issue again, so I'm gonna reference a follow up I made:
https://github.com/futuretap/InAppSettingsKit/issues/284#issuecomment-71538714

My issue is still persisting and I cannot seem to track down the issue. I was subclassing `IASKAppSettingsViewController`, but I have just reverted to using the standard view controller (for now) to minimize discrepancies. I still cannot get the selection to take. I am only using `Root.inApp.plist` because I don't want to have to maintain a separate file for each device type. I deleted all the other Root*.plist files from the bundle. I pretty much  reproduced what I'm doing in the Demo app, but am still experiencing the issue in the video above. I've done a fresh install to device, clear derived data, and done a clean build...the whole nine yards. 

```
IASKAppSettingsViewController *settingsVC = [[IASKAppSettingsViewController alloc] init];
 [navigationController pushViewController:settingsVC animated:NO];
```

Settings.bundle
```
ls -la Settings.bundle/
total 80
drwxr-xr-x@   9 nathanmock  staff    306 Jan 26 12:45 .
drwxr-xr-x@ 120 nathanmock  staff   4080 Jan 26 12:55 ..
-rwxr-xr-x@   1 nathanmock  staff   2573 Jan 19 03:55 Advanced.plist
-rwxr-xr-x@   1 nathanmock  staff  17789 Jan 19 03:55 Complete.plist
-rwxr-xr-x@   1 nathanmock  staff   4098 Jan 26 10:52 Root.inApp.plist
drwxr-xr-x@   3 nathanmock  staff    102 Jan 19 03:55 de.lproj
drwxr-xr-x@   3 nathanmock  staff    102 Jan 19 03:55 en.lproj
```

Any ideas as to what else can be going on or implementation gotchas?

**Comment by futuretap** [comment]
reopened #284, closing this.
