### ISSUE TITLE
problem with hiddenKeys in PSChildPanes

### ISSUE THREAD

**Issue by mournblade** [futuretap/InAppSettingsKit#288]
I have a view with some child panes. I wanted to hide some of the keys in the child panes. It didn't work, but does in the example (login is hidden in "advanced" for example). 

After hours of debugging i have found the 'issue'. It works in the example because the setFile method works differently than in my pod.

example:
- (NSString*)file {
	if (!_file) {
		return @"Root";
	}
	return _file;
}

latest:
- (NSString*)file {
	if (!_file) {
		self.file = @"Root";
	}
	return _file;
}

This results in that when I call the
self.hiddenKeys = [NSSet setWithObjects:@"testGoRoot", @"logout", @"radiogroup", @"radiogroup", nil];

on row 324, in the sethiddenkeys method:
if (!_reloadDisabled) [self.tableView reloadData];

this results in setfile being called on row 71:
_settingsReader = [[IASKSettingsReader alloc] initWithFile:self.file];

and in the setfile method, on row 97:
_hiddenKeys = nil;

So later, when i go into the childpane, hiddenkeys gets set to nil, rather then the value i had initially set.

I got around this by, in viewdidload, just calling self.file; but this feels like a hacky solution.

I hope this makes sense.

**Comment by futuretap** [comment]
Thanks for the detailed report. Indeed I oversaw this side effect in my fix of #284. I hope that we can resolve this safely (not having other unwanted side effects) by not touching `_hiddenkeys` in `-setFile:`. Please try the latest version.
