### ISSUE TITLE
IASKAppSettingsViewController crashes on devices running iOS 6 when deployment target is set to iOS 6

### ISSUE THREAD

**Issue by flycatcher** [futuretap/InAppSettingsKit#290]
When deployment target is set to iOS 6, macro IASK_IF_IOS7_OR_GREATER is defined as an empty pass, and IASKAppSettingsViewController crashes on line 609, where cell.textLabel.textColor = tableView.tintColor;

To check the iOS version at run time, it'd probably be better to do this

#ifdef NSFoundationVersionNumber_iOS_6_1
#define IASK_IF_IOS7_OR_GREATER(...) \
if (floor(NSFoundationVersionNumber) > NSFoundationVersionNumber_iOS_6_1) \
{ \
__VA_ARGS__ \
}
#else
#define IASK_IF_IOS7_OR_GREATER(...) \
if (FALSE) \
{ \
__VA_ARGS__ \
}
#endif

Here is a stack trace:

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UITableView tintColor]: unrecognized selector sent to instance 0x1dce1c00'

Last Exception Backtrace:
0   CoreFoundation                       0x32f062a3 __exceptionPreprocess + 163
1   libobjc.A.dylib                      0x3ab8697f objc_exception_throw + 28
2   CoreFoundation                       0x32f09e07 -[NSObject(NSObject) doesNotRecognizeSelector:] + 168
3   CoreFoundation                       0x32f08531 ___forwarding___ + 390
4   CoreFoundation                       0x32e5ff68 _CF_forwarding_prep_0 + 22
5   XYZ                           0x0048b655 -[IASKAppSettingsViewController tableView:cellForRowAtIndexPath:] (IASKAppSettingsViewController.m:603)
6   UIKit                                0x34d5954d -[UITableView(UITableViewInternal) _createPreparedCellForGlobalRow:withIndexPath:] + 410
7   UIKit                                0x34d3e313 -[UITableView(_UITableViewPrivate) _updateVisibleCellsNow:] + 1308
8   UIKit                                0x34d557cf -[UITableView layoutSubviews] + 204

**Comment by futuretap** [comment]
Should be fixed in a8200b94d92384ba1c79be2ecf4ac537bde1e6cc (version 2.3.4).

**Comment by flycatcher** [comment]
Sorry, but no, this crash began with 2.3.4 due to the introduction of this macro IASK_IF_IOS7_OR_GREATER.
