### ISSUE TITLE
title not being set properly in child views

### ISSUE THREAD

**Issue by mournblade** [futuretap/InAppSettingsKit#291]
Hi, 

i have a situation where i need to do some different stuff in my child views. I have concluded that the best (only?) way is for me to check the "title" in viewdidload when the child view is loaded, like this:

if([self.title isEqualToString:MY_SPECIAL_CHILD_VIEW]){
           //fetch data from my server
        }

However, there is a problem with your IASKAppSettingsViewController code, starting at row 710:

targetViewController.delegate = self.delegate;
targetViewController.delegate = self.delegate;
targetViewController.settingsStore = self.settingsStore;
----PROBLEM targetViewController.file = specifier.file;
targetViewController.hiddenKeys = self.hiddenKeys;
targetViewController.title = specifier.title;

When you set the file, the 'setFile' method gets called. And on row 95 in that method:
self.tableView.contentOffset = CGPointMake(0, 0);

Setting the contentOffset causes the view to load, resulting in that ViewDidLoad gets called BEFORE hidden keys, or even more importantly, the title gets set to the key, since that happens two rows below.
Since those then always will be nil, i can't use them.

It would be great if at least those two rows could get moved up before the file row so that it has the correct title when viewdidload gets called.

**Comment by futuretap** [comment]
Why don't you overwrite `-setFile:` in your subclass? Relying on the title being already set in viewDidLoad is not recommended.
