### ISSUE TITLE
Dynamic Text AutoLayout Issue when using Accessibility Fonts

### ISSUE THREAD

**Issue by lismondbernard** [futuretap/InAppSettingsKit#293]
When larger dynamic text sizes are selected, the fonts are not in alignment with each other.  In Apple's Settings App, the Font does not respond to the larger Accessibility Fonts probably for this reason.
Here is an image attached with a sample:

![image](https://cloud.githubusercontent.com/assets/684132/6133757/2f94d4fa-b12a-11e4-951a-adb8344fb628.png)

two issues 

1) height and alignment of PRIVACY item
2) vertical alignment of text within single-line cells

**Comment by futuretap** [comment]
Happy to accept a pull request!

**Comment by lismondbernard** [comment]
Will create a pull request once we resolve some other bugs not related to IASK in our app, but should have something in a couple weeks.

**Comment by futuretap** [comment]
A lot has changed since 2015. Closing this for now. Feel free to comment if this is still relevant.
