### ISSUE TITLE
Cannot localize IASKOpenURLSpecifier url

### ISSUE THREAD

**Issue by MarkusSvensson** [futuretap/InAppSettingsKit#294]
I need a localized URL for a IASKOpenURLSpecifier. It does not seems to work. This is what I tried:
```xml
<dict>
	<key>File</key>
	<string>LINK_URL</string>
	<key>Title</key>
	<string>LINK_TEXT</string>
	<key>Type</key>
	<string>IASKOpenURLSpecifier</string>
</dict>
```

Adding LINK_URL in en.lproj/Root.strings does not work. Replacing LINK_URL with a string like "http://cnn.com" works fine. The other string LINK_TEXT works fine.

Is it not possible to extract the url to a localized parameter?

Thanks in advance

**Comment by futuretap** [comment]
Added in ac14ba35a5377acdd83a9bd78ac2bddefbd78d4e (2.4.4).

**Comment by MarkusSvensson** [comment]
Thanks!
