### ISSUE TITLE
settingsViewControllerDidEnd only called on dismiss

### ISSUE THREAD

**Issue by edasque** [futuretap/InAppSettingsKit#306]
Am I right in thinking that settingsViewControllerDidEnd is only called in the Modal alternative and not in the Push or TabController version. I think that's because dismiss is only called in the Modal as part of the present/dismiss calls.

Therefore a TabController based IASKAppSettingsViewController (and similarly a Push based one) would need to respond to other events (maybe a tab change) to re-configure the app.

**Comment by futuretap** [comment]
That's correct, yes.
