### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by pcantrell** [futuretap/InAppSettingsKit#308]
Project currently does not build with Carthage.

Fixing this would require adding a framework target with a shared build scheme.

**Comment by ryanbooker** [comment]
There is already a PR for this… any chance of it being accepted?

https://github.com/futuretap/InAppSettingsKit/pull/309

**Comment by mattijsf** [comment]
+1 Really need this. The Carthage build system is very commonly used as dependency management nowadays.
