### ISSUE TITLE
Slider custom view

### ISSUE THREAD

**Issue by VrasidasP** [futuretap/InAppSettingsKit#310]
I saw somewhere that IASKPSSliderSpecifierViewCell is not meant to be subclassed. 

I would like a layout like this:
![scr](https://cloud.githubusercontent.com/assets/6231277/9054014/7215f4d2-3a85-11e5-9c64-f7d65898af39.png)

How can I create new type of cell to implement like that? The documentation is a bit unclear on that.
Thanks!

**Comment by futuretap** [comment]
IASK directly allocates the slider cell so it would not recognize your subclass.

I recommend building a custom view. See IASKCustomViewSpecifier in the documentation: https://github.com/futuretap/InAppSettingsKit#iaskcustomviewspecifier
