### ISSUE TITLE
IASKTextViewSpecifier

### ISSUE THREAD

**Issue by rlaferla** [futuretap/InAppSettingsKit#315]
A critical missing specifier in IASK is a multi-line text view.  While this "can" be implemented using a IASKCustomViewSpecifier, it really should be a first class citizen.  Therefore, I suggest adding support for a IASKTextViewSpecifier.

**Comment by futuretap** [comment]
I totally agree. I'm currently working on that since I need that feature in one of my apps.

**Comment by rlaferla** [comment]
I actually have code already.  Just polishing it off.  Want me to commit?

**Comment by futuretap** [comment]
Me too but why not! I'll take a look.

**Comment by rlaferla** [comment]
I created a pull request.  Take a look.  I should note that there is a specifier option for the # of lines called NumberOfLines.  It defaults to 3.

**Comment by futuretap** [comment]
My code uses a resizing text view that automatically adapts to the entered text and the available screen real estate. If the textView doesn't fit on the screen, `scrollEnabled=YES` is set. I think that's more flexible than predefining the number of lines.

**Comment by rlaferla** [comment]
Many times I need to limit the number of lines.  How about making it dynamic if no NumberOfLines is present or it is set to 0?  I think developers will appreciate having both options.

**Comment by futuretap** [comment]
Take a look at the code. We could certainly add a NumberOfLines parameter.

**Comment by futuretap** [comment]
Noticed I hadn't merged my feature branch so far. Done!
