### ISSUE TITLE
Pop to IASKSettingsViewController after change UITabBar.viewControllers

### ISSUE THREAD

**Issue by st400** [futuretap/InAppSettingsKit#324]
I add a observer for kIASKAppSettingChanged notification and would like to change the tabBar viewControllers:

```
[[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(settingsChanged:) name:kIASKAppSettingChanged object:nil];
```

```
- (void) settingsChanged: (NSNotification*) notification {
    NSMutableArray *tabs = [NSMutableArray array];
    [tabs addObjectsFromArray:self.tabBarController.viewControllers];

    UIViewController *newViewController = [[UIViewController alloc] init];
    newViewController.tabBarItem = [[UITabBarItem alloc] initWithTitle:@"New tab" image:nil tag:0];
    [tabs addObject:newViewController];

    self.tabBarController.viewControllers = tabs;
}
```

After update the viewControllers the IASKAppSettingsViewController pop to the root SettingsViewController. Is the behavior wanted?

How can I change the tabbar viewControllers by pressing the toggle buttons without change the current view?

![iask](https://cloud.githubusercontent.com/assets/684146/11753537/d8a4e200-a045-11e5-9d9a-a4b7acd33e20.gif)

**Comment by futuretap** [comment]
How should that be an issue in IASK? You're replacing all view controllers of the tab bar controller so I do expect that they are all thrown back to root.

**Comment by st400** [comment]
If I execute the same method (settingsChanged:) from a button within a custom UIViewController it behaves differently - they not thrown back.

**Comment by futuretap** [comment]
You can provide a sample project and I'll look into it when my time permits.

**Comment by futuretap** [comment]
Please check if the issue persists in the latest update and create a new issue if needed.
