### ISSUE TITLE
Unable to change tint color for title and back button

### ISSUE THREAD

**Issue by EpicDraws** [futuretap/InAppSettingsKit#325]
Using IASK, I am unable to change the back button color and arrow when used in a UINavigationController. I consistently control the tint color and title text attributes across my app, and this is the only controller that won't respond. It will use my navigation bars existing color, but won't let me change it before presenting. Further, I have found absolutely no way to change the back button text color or arrow color.

Thanks for an otherwise incredible library!

**Comment by futuretap** [comment]
This should work:

    	UINavigationBar.appearance.tintColor = UIColor.redColor;

**Comment by wkoszek** [comment]
@futuretap on the similar note: what's the easiest way to get `tintColor` inherited for toggle switches? By default they're light green, but since my app uses purple styling, I'd like to adjust this. Tried setting the `tintColor` for the prototype cell, but it didn't work.

**Comment by futuretap** [comment]
Did you try using the appearance proxy?

    UISwitch.appearance.tintColor = UIColor.purpleColor;

**Comment by wkoszek** [comment]
@funnel20 this seems to work great. Both `tintColor` and `onTintColor` work fine.

**Comment by funnel20** [comment]
@wkoszek That's awesome. 
However, I don't know why you sent this to me, as I wasn't involved in this issue.

**Comment by wkoszek** [comment]
@funnel20 sorry. GitHub nick autocompletion played a trick on me.

@futuretap this seems to work great. Both tintColor and onTintColor work fine.

**Comment by funnel20** [comment]
@wkoszek No worries :-)
