### ISSUE TITLE
wrong font size in iOS 9.2

### ISSUE THREAD

**Issue by lucastan** [futuretap/InAppSettingsKit#326]
The first two rows are child pane specs.
The last two rows are custom specs with (table view cell with Subtitle style), the last two rows have the right font size. 

I believe it's due to adjustFontSizeToFitWidth being true by default

![screen shot 2016-01-07 at 1 48 10 am](https://cloud.githubusercontent.com/assets/742503/12149817/c4dc1a9a-b4e0-11e5-912b-feca904aa129.png)

**Comment by futuretap** [comment]
This looks different in the IASK sample app. Can you provide a sample app reproducing the issue?
