### ISSUE TITLE
When the top row of a long multi-value list is checked, it's shown behind the Navigation Bar

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#331]
This can be reproduced with version 2.6.1 of the Sample Project (InAppSettingsKitSampleApp.xcodeproj), compiled with Xcode 7.2.1 on iPhone 5S.

Steps:
1) Either select the 2nd Tab, or use both options on first tab.
2) In section "Multiple values", select "Update at Launch", which is by default set to "maybe"
3) The detail view is shown, where "Maybe" is the top row, and mostly hidden behind the Navigation Bar:
![screen shot 2016-02-16 at 11 17 26](https://cloud.githubusercontent.com/assets/2139844/13073429/054fe3d0-d49f-11e5-8bb0-fb4abcb10741.png)

I spent several hours trying to solve it, by checking 'contentInsets' and other properties, but these seem all correct.

The only work-around I could come up with is the following.
In 'viewWillAppear:' of IASKSpecifierValuesViewController:
- When row 0 is checked, use a rect with origin (0, 0) and call 'scrollRectToVisible:'
- For other checked rows, the indexPath row in 'scrollToRowAtIndexPath:' is subtracted by 1.

**Original**
```
// Make sure the currently checked item is visible
[_tableView scrollToRowAtIndexPath:_selection.checkedItem
                  atScrollPosition:UITableViewScrollPositionMiddle animated:NO];
```

**Modified**
```
// Work-around for the top row, which is always shown behind the Navigation Bar.
NSInteger checkedRow = _selection.checkedItem.row;
if (checkedRow == 0) {
    // To fully show the top row, use a rect with origin (0, 0):
    [_tableView scrollRectToVisible:CGRectMake(0, 0, _tableView.bounds.size.width, [_tableView rowHeight])
                           animated:NO];
}
else {
    // For all other rows, subtract 1 row, to ensure the checked row is below the Navigation Bar:
    [_tableView scrollToRowAtIndexPath:[NSIndexPath indexPathForRow:checkedRow-1 inSection:_selection.checkedItem.section]
                      atScrollPosition:UITableViewScrollPositionMiddle animated:NO];
}
```
Repeating the above 3 steps with this code shows correct behaviour:
![screen shot 2016-02-16 at 11 25 43](https://cloud.githubusercontent.com/assets/2139844/13073631/1ac6136e-d4a0-11e5-8e86-ae490e26c299.png)

I understand that this might not be Production code, but it can be a temporary work-around until you have found the root-cause.

**Comment by futuretap** [comment]
Thanks for bringing this to my attention. I think my fix is a bit cleaner than the one you provided.

**Comment by funnel20** [comment]
Yours is a real fix, especially since it now always respects the option UITableViewScrollPositionMiddle.
Thanks a lot!
