### ISSUE TITLE
Not work for cocoapods 1.0.0.beta.4

### ISSUE THREAD

**Issue by liuwin7** [futuretap/InAppSettingsKit#332]
Using Cocoapods to integrate InAppSettingsKit with my project failed with the Error 
`Resource "xxx" not found. Run 'pod install' to update the copy resources script.`.

Looking the sh file, find that when executing installing resources using this
` install_resource "${BUILT_PRODUCTS_DIR}/InAppSettingsKit.bundle" ` 

But there is no bundle file in all InAppSettingsKit!!!

**Comment by liuwin7** [comment]
Need you update your  InAppSettingsKit.podspec file?
For the line
`s.resource_bundles		= {"InAppSettingsKit" => "InAppSettingsKit/Resources/*"}`

using the line below to replace the line above
 
`s.resource_bundles		= {"InAppSettingsKit" => "InAppSettingsKit/Resources/InAppSettingsKit.bundles"}`

and add InAppSettingsKit.bundles to Resources.

**Comment by futuretap** [comment]
Unfortunately I could not reproduce the issue in a new test project with cocoapods 1.0.0.beta.4 and this Podfile:

```
use_frameworks!
project 'SettingsDemo'

target 'SettingsDemo' do
  pod 'InAppSettingsKit'
end
```

Can you post a test project reproducing the issue?

**Comment by liuwin7** [comment]
If my Podfile doesn't include `use_frameworks!`.  Xcode will give me that error when building my project.
My Podfile:
`platform :ios, '7.0'

target 'InAppSettingsKitWithPod' do
    pod 'InAppSettingsKit'
end`

**Comment by liuwin7** [comment]
If my Podfile doesn't include `use_frameworks!.` Xcode will give me that error when building my project.
My Podfile:
```ruby
platform :ios, '7.0'
target 'InAppSettingsKitWithPod' do
    pod 'InAppSettingsKit'
end
```

**Comment by futuretap** [comment]
Thanks, I can reproduce the issue now. However, I believe this is a bug in CocoaPods (see linked issue). For now, I recommend using the stable CocoaPods 0.39.0.

**Comment by liuwin7** [comment]
Ok, Thanks! We can only wait for CocoaPods fixing it up.

**Comment by futuretap** [comment]
@liuwin7 Can you check if CocoaPods 1.0 beta 5 fixes the issue?

**Comment by liuwin7** [comment]
@futuretap Ok, I'll try. Thank you!
