### ISSUE TITLE
When going back from a detail tableview, the parent tableview sometimes scrolls up

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#333]
This behaviour is visually unattractive.

It can be reproduced with version 2.6.2 of the Sample Project (InAppSettingsKitSampleApp.xcodeproj), compiled with Xcode 7.2.1 on iPhone 5S (iOS 9.2).
The issue only occurs when scrolled to the bottom of the parent view (see step 4).

**Steps**

1. Launch sample app
2. Select Modal on the Featured tab
3. Scroll down and select "Complete List"
4. Scroll completely down to the bottom, so "Another entry" is visible:
![before](https://cloud.githubusercontent.com/assets/2139844/13457838/6fd10582-e06a-11e5-8e02-68a26efaa455.png)
5. Select "Separate highlighted image" row
6. Press back
7. The target Tableview scrolls up, so "Another entry" is NOT visible anymore at the bottom:
![after](https://cloud.githubusercontent.com/assets/2139844/13457846/7947f620-e06a-11e5-93e4-463da73a7664.png)

**Analysis**
This happens in 'viewWillAppear:' of IASKAppSettingsViewController, in this snippet:
```
if(selectedIndexPath) {
    [self.tableView reloadRowsAtIndexPaths:[NSArray arrayWithObject:selectedIndexPath]
                          withRowAnimation:UITableViewRowAnimationNone];
    // and reselect it, so we get the nice default deselect animation from UITableViewController
    [self.tableView selectRowAtIndexPath:selectedIndexPath animated:NO scrollPosition:UITableViewScrollPositionNone];
}
```
Just to pinpoint the cause, when I uncomment these 2 lines, the scrolling doesn't happen (of course reloading doesn't too).
I don't have a solution, nor a work-around.

This might be related to https://github.com/futuretap/InAppSettingsKit/issues/331, where the height of the transparent Navigation Bar wasn't taken into account while scrolling.
Any help is appreciated.

**Comment by futuretap** [comment]
It seems to help to put `[super viewWillAppear:animated];` at the top instead of at the end of the method. Just not sure if that was intentional or if it has any side effects. Can you check?

**Comment by funnel20** [comment]
Wow, that resolves the issue. Great idea.

**Comment by funnel20** [comment]
Thanks. I can confirm I didn't see side effects.
The purpose of those 2 lines of code are to highlight/animate a newly selected value from a multi-value child tableview. This is still executed properly, but now without the annoying scrolling.

**Comment by futuretap** [comment]
Great, thanks for confirming. Is pushed as 2.6.3 to CocoaPods.
