### ISSUE TITLE
Title not shown for IASKButtonSpecifier

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#334]
When adding IASKButtonSpecifier to my *.plist, the title is not shown in the tableview, just an empty clickable row.

**Situation**
- Xcode 7.2.1 on iPhone 5S (iOS 9.2).
- Bundle is called: InAppSettings.bundle
- Main entry: Root.plist
- It has a bunch of other Child *.plist files

I add the following Dictionary (from the Sample Project InAppSettingsKitSampleApp.xcodeproj) to the Root.plist:
```
        <dict>
			<key>Key</key>
			<string>ButtonDemoAction1</string>
			<key>Title</key>
			<string>Button Action 1</string>
			<key>Type</key>
			<string>IASKButtonSpecifier</string>
		</dict>
```
When running the app, it only shows an empty line:
![screen shot 2016-03-02 at 17 02 03](https://cloud.githubusercontent.com/assets/2139844/13466073/ad9d3218-e098-11e5-962c-e9f2bd278feb.png)

**Analysis**
In 'tableView cellForRowAtIndexPath:' of IASKAppSettingsViewController, there is an ELSE IF condition for kIASKButtonSpecifier.
The result for the following line, is an empty string:
```
cell.textLabel.text = [value isKindOfClass:[NSString class]] ? [self.settingsReader titleForId:value] : specifier.title;
```
Tested in the debugger and while `value` is an NSString, `[self.settingsReader titleForId:value]` is empty.

**Solution / work-around**
I'm not sure what the difference between `[self.settingsReader titleForId:value]` and `specifier.title` is. Except that I defined `specifier.title` myself in the *.plist as "Button Action 1".
Hence I added a check if `[self.settingsReader titleForId:value]` isn't empty. If empty, use `specifier.title`.
As a result, the above code snippet is changed to:
```
cell.textLabel.text = [value isKindOfClass:[NSString class]] ? ([[self.settingsReader titleForId:value] length] > 0 ? [self.settingsReader titleForId:value] : specifier.title) : specifier.title;
```
Now the title is shown correctly:
![screen shot 2016-03-02 at 17 11 26](https://cloud.githubusercontent.com/assets/2139844/13466379/f8718d10-e099-11e5-8a64-8ba5baadbc19.png)

Do you have any clue why `[self.settingsReader titleForId:value]` is empty?

**Comment by futuretap** [comment]
The idea of the code is that you can store a value for the key in `NSUserDefaults` (or whatever store you use). Then IASK takes that dynamic value as the button title. So I assume there is a value (specifically: the empty string) for that key in your user defaults.

You're right that we should catch this. A bit shorter version would be:

    cell.textLabel.text = ([value isKindOfClass:NSString.class] && [self.settingsReader titleForId:value].length) ? [self.settingsReader titleForId:value] : specifier.title;

**Comment by funnel20** [comment]
Thanks for the explanation.
So If I understand correctly, to get the value in the `settingsReader`, I should add the desired title to my NSUserDefaults, or add the value as 'Default Value' key to *.plist.

But when I look in to Sample Project, I don't see where that's done. I only see the button title "Button Action 1" in 3 *.plist files, with only Key, Title and Type keys. 
Can you tell me how this button title was displayed, even with the 'old' code?

I tested your new code, both in my Project and the Sample Project, and it works.

**Comment by futuretap** [comment]
You can see this feature in action for the *Login* button. When you tap it, it changes to *Logout*. The corresponding code is in `MainViewController.m:218` of the sample app.
