### ISSUE TITLE
The Sample Project doesn't compile, because new files IASKTextView.* and IASKTextViewCell.* are not added to Project

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#336]
Used Xcode 7.2.1 on iPhone 5S Simulator (iOS 9.2):

> InAppSettingsKit-master/InAppSettingsKit/Controllers/IASKAppSettingsViewController.m:28:9: 'IASKTextViewCell.h' file not found

When adding the 4 files to the Views subfolder, it works.

**Comment by futuretap** [comment]
Hm, could not reproduce this with a clean checkout.

**Comment by funnel20** [comment]
I downloaded the ZIP-file from https://github.com/futuretap/InAppSettingsKit directly. Can that be the cause?

**Comment by funnel20** [comment]
From the commit log https://github.com/futuretap/InAppSettingsKit/commit/e5a4bf236f1cbd5d5a5eee49d562c9ce3ae43247 I see that the new files are added to the project file project.pbxproj of InAppSettingsKit.xcodeproj, but not to that of InAppSettingsKitSampleApp.xcodeproj.

**Comment by futuretap** [comment]
I also downloaded the ZIP but only tested the IASKSampleAppStaticLibrary target from the xcworkspace. My fault, I totally forgot about this additional xcodeproj.
