### ISSUE TITLE
Selection broke up with tab bar

### ISSUE THREAD

**Issue by 0xC01L** [futuretap/InAppSettingsKit#338]
I have a UITabBarController with IASK as a tab.
1) Open IASKSpecifierValuesViewController for multi-value item
2) Tapping on cell will remove checkmark from selected cell and place it on the tapped cell. At this moment all is working fine
2) Go to an other tab, then get back to IASK
3) Now tapping on cell will not reload table view
It happens probably because of this line `_selection.tableView = nil;` in `viewDidDisappear`.
Because when we go back to controller table view wasn't set up again on `viewDidAppear`. Also I can't see a reason for making it nil on `viewDidDisappear` at all.

**Comment by flyinghead** [comment]
I'm experiencing the same issue as well. Thank you for the work-around.

**Comment by wkoszek** [comment]
@flyinghead Do you think we could just remove these 2 lines? Can you make a pull request?

**Comment by flyinghead** [comment]
Done. I have removed the now empty method. See PR #361

**Comment by futuretap** [comment]
I also don't understand what `_selection.tableView = nil;` is good for. @nschum since you wrote the code back then, do you remember?

**Comment by gereons** [comment]
I believe this was already fixed in #363. BTW, it'd be great if you could bake that into a point release :)

**Comment by futuretap** [comment]
Please check if this is fixed in 2.8.1. (For some reason, the GH Web UI doesn't show it even though the git repo and CocoaPods do have it.)

**Comment by gereons** [comment]
Works for me, as expected. Thanks!
