### ISSUE TITLE
there is different when I run InAppSettingsKit Demo in OrientationLandScape on the iPad

### ISSUE THREAD

**Issue by ShowerLi1991** [futuretap/InAppSettingsKit#339]
rt

**Comment by futuretap** [comment]
What do you mean?

**Comment by ShowerLi1991** [comment]
[https://raw.githubusercontent.com/ShowerLi1991/SLTumblr/master/屏幕快照%202016-03-25%2015.12.10.png](url)
[https://raw.githubusercontent.com/ShowerLi1991/SLTumblr/master/屏幕快照%202016-03-25%2015.12.17.png](url)
[https://raw.githubusercontent.com/ShowerLi1991/SLTumblr/master/屏幕快照%202016-03-25%2015.12.28.png](url)
