### ISSUE TITLE
Possibility of reordering items by user?

### ISSUE THREAD

**Issue by bagage** [futuretap/InAppSettingsKit#345]
I am not sure if it should be possible but I have a list of `PSToggleSwitchSpecifier` options that I would like to be sortable by user: 
```
Enable option 1: <YES | NO>
Enable option 2: <YES | NO>
Enable option 3: <YES | NO>
```
Could be sorted for instance to:
```
Enable option 3: <YES | NO>
Enable option 1: <YES | NO>
Enable option 2: <YES | NO>
```
Is there any way to do it with InAppSettingsKit easily, or must I implement it on my own?

Thanks!

**Comment by futuretap** [comment]
This is currently not possible in IASK. Would be a great addition, though. If you could find a way to do it in a generic way, I'd love to accept a pull request!
