### ISSUE TITLE
When we use textFieldShouldBeginEditing to test if a textfield is firstResponder, it results in an error

### ISSUE THREAD

**Issue by sunbohong** [futuretap/InAppSettingsKit#348]

**Comment by sunbohong** [comment]
https://github.com/sunbohong/Demo-348

I create a sample for this issue.

**Comment by sunbohong** [comment]
https://github.com/sunbohong/Demo-348/blob/master/Demo%20348/ViewController.m#L25-L34

```
2016-07-06 14:49:19.923 Demo 348[2042:1093332] the currentFirstResponder is left
2016-07-06 14:49:19.926 Demo 348[2042:1093332] right
```

**Comment by futuretap** [comment]
I downloaded your sample app but don't see where the "error" is. Can you please describe what you'd expect and what IASK actually does?

**Comment by sunbohong** [comment]
When i select `left textfield`,the `currentFirstResponder` should be  `left textfield`.

But as you can see from `console`, the `IASKAppSettingsViewController`'s `currentFirstResponder` property is `right textfield`

**Comment by futuretap** [comment]
I see. Of course this is only an issue in combination with your `IQKeyboardManager` library. Nevertheless, I agree, it's right to switch to `-textFieldDidBeginEditing:`. Can you send your fix as a pull request for easy merging?
