### ISSUE TITLE
reverting toggled values programmatically

### ISSUE THREAD

**Issue by eliburke** [futuretap/InAppSettingsKit#353]
I'm merging the latest commits into my fork and reviewing local modifications. A very long time ago I modified IASKAppSettingsViewController's implementation of toggledValue to post kIASKAppSettingChanged with the toggle object rather than self:
```
    [[NSNotificationCenter defaultCenter] postNotificationName:kIASKAppSettingChanged
                                                        object:toggle
                                                      userInfo:[NSDictionary dictionaryWithObject:[self.settingsStore objectForKey:[toggle key]]
                                                                                           forKey:[toggle key]]];
```

This allows me to catch the notification, perform some logic, and possibly revert the value.
```
    NSString * key;
    IASKSwitch * toggle;
    if ([notif.object isKindOfClass:[IASKSwitch class]]) {
        toggle = notif.object;
        key = [toggle key];
    } else {
        key = notif.object;
    }
    if ([toggle isOn] && someConditionFailed) {
        [toggle setOn:NO animated:YES];
        // warn user
    }
```

Is there a better way to accomplish this? Is it something that you would want a PR for?

**Comment by futuretap** [comment]
Did you try to simply change the userDefaults value? IASK listens for such changes and should dynamically update its UI.
