### ISSUE TITLE
IASKPerformSegue

### ISSUE THREAD

**Issue by kristian** [futuretap/InAppSettingsKit#357]
As an alternative for specifying a IASKViewControllerClass for child pane elements, it would be helpful to have an IASKPerformSegue option. IASK could trigger the `performSegueWithIdentifier`, this would significantly clean up the required code in the app. At the moment you'd have to define a IASKButtonSpecifier to perform the segue in the delegate method.

**Comment by futuretap** [comment]
This is a great idea, I'd gladly accept a pull request! ;)

**Comment by kristian** [comment]
Sure 👍  Feel free to pull #358. Tested and ready to merge.

**Comment by futuretap** [comment]
Thanks Kristian!

**Comment by kristian** [comment]
Welcome. Thanks for merging Ortwin. Will you release this as a new pod update? This would be highly anticipated. Thanks a ton!

**Comment by futuretap** [comment]
Yes, hold on. Merging another PR.

**Comment by kristian** [comment]
Perfect! No hurry, just wanted to check. :+1:
