### ISSUE TITLE
CFURLCreateStringByReplacingPercentEscapesUsingEncoding() deprecated in iOS 9.0

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#359]
In IASKAppSettingsWebViewController.h, CFURLCreateStringByReplacingPercentEscapesUsingEncoding() is used, which is deprecated in iOS 9.0.
Xcode suggest to use CFURLCreateStringByReplacingPercentEscapes() "which always uses the recommended UTF-8 encoding."

The code will then be (last input argument 'kCFStringEncodingUTF8' is removed):

```
value =  CFBridgingRelease(CFURLCreateStringByReplacingPercentEscapes(kCFAllocatorDefault,
                                                                                      (CFStringRef)value,
                                                                                      CFSTR("")));
```

CFURLCreateStringByReplacingPercentEscapes() is supported since iOS 2.0, so it can be used safely.

**Comment by PGSeattle** [comment]
+1 for funnel20's suggestion.
value =  CFBridgingRelease(CFURLCreateStringByReplacingPercentEscapes(kCFAllocatorDefault,
																							 (CFStringRef)value,
																							 CFSTR("")));
