### ISSUE TITLE
Storyboard Demo Lexical or Preprocessor Issue

### ISSUE THREAD

**Issue by merktassel** [futuretap/InAppSettingsKit#365]
I was having an issue with the done button not returning to the previous view, and decided to take a look at the storyboard demo first before posting an issue. However, I was unable to get it to run using the latest release of Xcode 8.

I opened `InAppSettingsKitSampleAppStoryboard.xcodeproj` located at `InAppSettingsKit/InAppSettingsKitSampleAppStoryboard` and Xcode immediately suggested updating the project to use the recommended settings. I declined and opted to try running the demo without changing anything other than the team provisioning profile. It produced the following error, with both original settings and the recommended settings:

**Lexical or Preprocessor Issue**

```
/Users/user/Desktop/InAppSettingsKit/InAppSettingsKitSampleAppStoryboard/InAppSettingsKitSampleAppStoryboard/SettingsViewController.h:9:9: 'InAppSettingsKit/IASKAppSettingsViewController.h' file not found
```

I noticed `libInAppSettingsKit.a` was red in the project navigator. Any ideas on what I could be doing wrong?

**Comment by futuretap** [comment]
Please check if the issue persists in the latest update and create a new issue if needed.
