### ISSUE TITLE
IASKSettingsDelegate method rename suggestion

### ISSUE THREAD

**Issue by VilemKurz** [futuretap/InAppSettingsKit#367]
`- (CGFloat)tableView:(UITableView*)tableView heightForSpecifier:(IASKSpecifier*)specifier;`

might be renamed to heightFor**CustomView**Specifier:

It is confusing as it is now, because it implies the delegate can set height for all types of specifiers. In reality, all are 44 except kIASKCustomViewSpecifier which is actually the only type getting its height from this delegate method.

**Comment by futuretap** [comment]
We did a big delegate method renaming in 3.0. Hope it addresses your needs.
