### ISSUE TITLE
Can IASK work with more than one plist

### ISSUE THREAD

**Issue by jmcazaux** [futuretap/InAppSettingsKit#369]
Hi there,
I have a possibly unusual use case.

First, I would like to use custom editors for some settings (user can select colors).
If I read correctly, this is feasible with IASK.

I have not found a answer though for my second issue.

Our app is fairly broad with 3 or 4 different "areas" and we would like to have settings on an "area" basis.
This is definitely not possible with standard settings but is it possible with IASK?

This could be either thru different plist or different Childpanes in the same plist but then it would require being able to start the editor from a given Childpane.

Many thanks for your answer.

**Comment by futuretap** [comment]
This is not a support forum. Please ask on StackOverflow with tag `inappsettingskit`.
