### ISSUE TITLE
Crash on done button click when PSGroupSpecifier's title is nil

### ISSUE THREAD

**Issue by zj299792458** [futuretap/InAppSettingsKit#371]
HI. I need to remove Title attribute of all "PSGroupSpecifier" for reasonable group gap when title is missing, but it crashes as soon as I click done button on that page. If I add Title back everything is just fine.

It crashes at 
- (UIView *)tableView:(UITableView*)tableView viewForHeaderInSection:(NSInteger)section
in IASKAppSettingsViewController.m 

it seems making it return nil can fix it without side-effect？

**Comment by futuretap** [comment]
Can you paste the complete backtrace? The code should not crash except if you configured a delegate without holding onto it strongly.

**Comment by zj299792458** [comment]
@futuretap 
Thank you for your reply. 
It just gets stuck there in a red label "EXC_BAD_ACCESS" without backtrace printed.

I inherit IASKAppSettingsViewController in a subclass and assign the delegate to the subclass itself, without implementing (tableView:viewForHeaderInSection:). So it triggers super class's tableView:viewForHeaderInSection: method, which triggers delegate(subclass) again. It seems a dead loop. That may be the problem.

But the strange thing is, returning nil on this method doesn't have any affects. So implementing the method in subclass and returning nil solve the problem.

**Comment by futuretap** [comment]
Please post a sample project and I can have a look.

**Comment by zj299792458** [comment]
@futuretap Sorry In my sample project the Done button doesn't trigger the tableView:viewForHeaderInSection:, it only triggers settingsViewControllerDidEnd, which is totally perfect. 🙁

It should be my problem. table view delegate is invoked incorrectly somewhere when done. 

Sorry for interruption, appreciate the help.
