### ISSUE TITLE
subclassing IASKSpecifierValuesViewController

### ISSUE THREAD

**Issue by FLKone** [futuretap/InAppSettingsKit#375]
Hi,

I'm trying to apply my own colors/theme to IASK.

With a `PSMultiValueSpecifier` setting, in current 2.8 branch, can we set a custom `IASKSpecifierValuesViewController` subclass so we can customize the cellForRowAtIndexPath ?

Thanks
(I posted about that on S/O but I'm not sure if it's a support question or a feature request :P)

**Comment by futuretap** [comment]
It's a support question. Answered on SO.
