### ISSUE TITLE
Support for UINavigationItemLargeTitleDisplayMode

### ISSUE THREAD

**Issue by Schaefers** [futuretap/InAppSettingsKit#377]
Would be nice to support this on iOS 11, because otherwise the ui looks different throughout the App.

https://developer.apple.com/documentation/uikit/uinavigationitemlargetitledisplaymode?language=objc

**Comment by futuretap** [comment]
It is already supported. Just enable `prefersLargeTitles` on your navigation bar.

**Comment by Schaefers** [comment]
Yeah, I already did this, but the title is small when the view is launched the first time. You have to scroll down to make the title big, is there any way to start the view with a big title?

**Comment by Schaefers** [comment]
It's working now, thanks for your help.

**Comment by zj299792458** [comment]
> It's working now, thanks for your help.

How? I encountered this problem too, appreciate any help.
