### ISSUE TITLE
Accessibility Larger Fonts Issue

### ISSUE THREAD

**Issue by jrustonapps** [futuretap/InAppSettingsKit#380]
Hello,

I am using this library in a number of my apps (great job by the way!) but I'm experiencing some issues when users have the larger fonts option in accessibility enabled. When the user selects one of the larger font sizes, the InAppSettingsKit screen in my apps completely breaks with text overlapping everywhere and it being completely unreadable in some places. Recently I've been getting quite a few e-mails about it. I have attached a screenshot.

![image](https://user-images.githubusercontent.com/4980957/34879062-4cef8902-f7ac-11e7-8031-2f9993436a6f.png)

Is there any plans to improve support for dynamic text (or to add an option to just use fixed font sizes instead)? In other parts of my apps that are not yet ready for dynamic text, using fixed font sizes seems to at least make the screen readable.

Thanks!

**Comment by futuretap** [comment]
I don't have plans to fix this right now, but will be gladly accepting a pull request.

**Comment by diederich** [comment]
I think this should be fixed with the recent update. Please feel free to reopen / create a new issue if there are still specific issues.
