### ISSUE TITLE
Fix to add UIAlertController UIAlertActionStyleCancel

### ISSUE THREAD

**Issue by n690rp** [futuretap/InAppSettingsKit#382]
I'd suggest adding this to keep mail compose from holding the view w/ no way to cancel when mail not configured.

line 874 IASKAppSettingsViewController.m
#if __IPHONE_OS_VERSION_MIN_REQUIRED >= __IPHONE_8_0
			UIAlertController *alert = [UIAlertController alertControllerWithTitle:NSLocalizedString(@"Mail not configured", @"InAppSettingsKit")
																		   message:NSLocalizedString(@"This device is not configured for sending Email. Please configure the Mail settings in the Settings app.", @"InAppSettingsKit")
																	preferredStyle:UIAlertControllerStyleActionSheet];
            [alert addAction:[UIAlertAction actionWithTitle:@"Cancel" style:UIAlertActionStyleCancel handler:nil]];
			[self presentViewController:alert animated:YES completion:nil];
#else

**Comment by clindsay** [comment]
@futuretap I created a pull request with this fix: https://github.com/futuretap/InAppSettingsKit/pull/392
