### ISSUE TITLE
- (CGSize)preferredContentSize implementation resized controller on iPad

### ISSUE THREAD

**Issue by sarsonj** [futuretap/InAppSettingsKit#383]
Hi,

what is reason for implementation of 

- (CGSize)preferredContentSize

in IASKSpecifierValuesViewController and IASKAppSettingsViewController?

When using FormSheet view style of settings controller, those methods made this controller looks too small / non standard on the iPad / iOS 11. When removed, the default size is used on the iPad. I didn't find any side effect of this remove - what is the reason to have it here?

**Comment by futuretap** [comment]
Not sure exactly but keep in mind that IASK is compatible down to iOS 8. I'm almost certain that this is needed for one of the older iOS releases. Closing this for now, please reopen if you can assure that it's not needed in any iOS version >= 8.0.

**Comment by triplef** [comment]
We had the same issue (tested on iOS 11/12/13) and fixed it by subclassing IASKAppSettingsViewController to return CGSizeZero from preferredContentSize and swizzling the method in IASKSpecifierValuesViewController. :)

Without testing all the way down to iOS 8 (which would probably require installing old Xcode versions), maybe these methods could just return a zero size on >= iOS 11. Would that be an an acceptable PR?

**Comment by futuretap** [comment]
OK, please submit a PR for it, thanks.
