### ISSUE TITLE
Images with multivalue item values

### ISSUE THREAD

**Issue by mournblade** [futuretap/InAppSettingsKit#393]
I would love for inappsettingskit to support defining an image to be displayed as an icon for each multi-choice in a PSMultiValueSpecifier, and have the image of the selected value to show up when the user selects and go back.

Is there any way to accomplish this right now without a totally custom component?

**Comment by futuretap** [comment]
This isn't possible right now. I suggest adding this to `IASKSpecifierValuesViewController` and `IASKAppSettingsViewController`. In `IASKSpecifier` there's already a `cellImage` and `highlightedCellImage` getter that should get you the images.

If you add this, please create a pull request, I'd be glad to merge it. ;)

**Comment by triplef** [comment]
FYI this was implemented last year via 76bbdd73db25e41ece38424b878f7fbab2254cb7.
