### ISSUE TITLE
Support for reading localisation strings from Localizable

### ISSUE THREAD

**Issue by mournblade** [futuretap/InAppSettingsKit#394]
I would love to have all my translation strings in the same place. Right now, i have almost all my stuff in the various Localizable.strings files, but the strings in my settings tab have to be in the Root.strings files.

It makes it cumbersome and error prone when i move translations to and from other programs that share the same translation strings.

Would be great if there was a way to make  InAppSettingsKit read its i18n strings from Localizable.

**Comment by futuretap** [comment]
While you can change the name of the strings file using the `StringsTable` specifier in the Settings.plist, it always searches strings files in the `Settings.bundle`. So currently this is not possible out of the box.

You could subclass `IASKAppSettingsViewController` and override the `settingsReader` getter to return a custom subclass of `IASKSettingsReader`. In your `IASKSettingsReader` subclass you need to override `-titleForId:` using your custom localizing method. Not pretty but it should work.

Feel free to implement a customization option for IASK and create a pull request! Closing this for now as I won't be able to implement this anytime soon.

**Comment by mournblade** [comment]
No worries, thanks for your detailed and helpful responses, now i know what the deal is :)
