### ISSUE TITLE
Hide Done button

### ISSUE THREAD

**Issue by soenkegissel** [futuretap/InAppSettingsKit#399]
I use this inside a UITabBar Navigation and there is no Done button in the top right corner needed for me.
Is there a way to hide it?

Thanks so much in advance.

**Comment by futuretap** [comment]
Simply set the navigationItem.rightBarButtonItem to nil, as in the sample app for the pushed view controller:

https://github.com/futuretap/InAppSettingsKit/blob/2fb2fa0d6a83f3b47ed18333cc4e028b5207268f/InAppSettingsKitSampleApp/Classes/MainViewController.m#L60
