### ISSUE TITLE
Swift example: Extend IASKAppSettingsViewController to catch button clicks

### ISSUE THREAD

**Issue by soenkegissel** [futuretap/InAppSettingsKit#400]
Hello,
I would really like to extend the IASKAppSettingsViewController to a custom one and just override the `func settingsViewController(_ sender: IASKAppSettingsViewController!, buttonTappedFor specifier: IASKSpecifier!)`

But my approach of extending IASKAppSettingsViewController and on viewDidLoad() assigning the delegate = self does not work. The settings get display no matter what I do, but the button never reacts to clicks.

Add more and more to my main viewcontroller is not what I want.

**Comment by futuretap** [comment]
If you're still affected, please send a sample app reproducing the issue and I'll gladly reopen the issue.
