### ISSUE TITLE
The vertical offset above a PSGroupSpecifier without title is smaller than in the iOS Settings app

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#401]
Run the sample app and select row "Complete List".
It shows a section with title "TEXT FIELDS".
The vertical offset is equal to that of the iOS Settings app with title (left):
![With-Title](https://user-images.githubusercontent.com/2139844/56800731-0a23c480-681c-11e9-9938-eb7419b9a862.png)

However, when removing the "Title" property from the *.plist file to create a section without title, the offset is much smaller than in the iOS Settings app (left):
![Without-Title](https://user-images.githubusercontent.com/2139844/56800844-4ce59c80-681c-11e9-8c5b-61229c455449.png)

Is it possible to create the same vertical offset as in the iOS Settings app when using no section title?

**Notes**
- All screenshots are created with Xcode 10.2 and iPhone Xs Simulator with iOS 12.2. The behaviour on a real device is the same (iPhone 7 with iOS 12.2).
- Using an empty string as title is no proper work-around, because the vertical offset in the iOS Settings app is slightly smaller when there is no title.

**Comment by futuretap** [comment]
Please let me know if that fix resolves the issue!

**Comment by funnel20** [comment]
@futuretap Wow, thank you for your fast response. And spot on!
I redid the test and added the new result on top of the previous image:

Fix has no negative effect on section **with** title:
![new-Title](https://user-images.githubusercontent.com/2139844/56814769-2174a900-6840-11e9-8116-dfdac8c084b2.png)

Fix sets correct height for section **without** title:
![new-noTitle](https://user-images.githubusercontent.com/2139844/56814788-289bb700-6840-11e9-90d2-cd4c1bdde840.png)

Awesome job, thanks.

**Comment by funnel20** [comment]
@futuretap  When do you think this will be released?

**Comment by futuretap** [comment]
was released yesterday

**Comment by funnel20** [comment]
Thank you
