### ISSUE TITLE
Deprecated API Usage / UIWebView

### ISSUE THREAD

**Issue by nhulsch** [futuretap/InAppSettingsKit#418]
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

while archiving an app with IASK and uploading it today to the App Store

**Comment by futuretap** [comment]
Yeah, we should switch to `WKWebView` or `SFSafariViewController`. The latter has a slightly different UI and is probably not as suitable for static local HTML pages.

Any preferences? Would you volunteer to create a pull request?

**Comment by billylo1** [comment]
> Yeah, we should switch to `WKWebView` or `SFSafariViewController`. The latter has a slightly different UI and is probably not as suitable for static local HTML pages.
> 
> Any preferences? Would you volunteer to create a pull request?

WKWebView would be better... if no one has started working on it, I can give it a try.  All my apps benefited from IASKSettings.  Would love to give back.

**Comment by futuretap** [comment]
We're already using `WKWebView`.

**Comment by billylo1** [comment]
> We're already using `WKWebView`.

Cool.  I just realized my Podfile is still pointing to 2.10.  thx.
