### ISSUE TITLE
Allow overriding system language

### ISSUE THREAD

**Issue by akirmse** [futuretap/InAppSettingsKit#426]
I wanted to add an in-app language setting.  I got everything else working, but I couldn't find a good way to change the strings file that InAppSettingsKit uses.  Might that be added?

**Comment by futuretap** [comment]
You can add a `StringsTable` key on the root level of your Settings.plist with the name of your strings file. Default is `Root`.

**Comment by akirmse** [comment]
Yes, I have that and it works fine if you want to use the system language.  What I want to is override the system language programmatically (via an in-app setting).  When the setting is changed, I'm able to override the app's string tables everywhere but in InAppSettingsKit.  In other words, the language of the app changes everywhere except for the InAppSettingsKit settings page.

**Comment by futuretap** [comment]
Probably your best bet is to swizzle `-[NSBundle localizedStringForKey:value:table:]`. However, your approach is likely to fail as soon as you display any system view controllers (like the share sheet), so I can't recommend it. Actually I can't recommend the whole idea of overriding the system language.
