### ISSUE TITLE
Create New Release

### ISSUE THREAD

**Issue by erikkerber** [futuretap/InAppSettingsKit#427]
We've been getting daily nagging emails from Apple every time we upload a build that links against UIWebView symbols.

It looks like InAppSettingsKit did in fact remove these last August (#418 / #419), but the last release was last June.

We can pin against the master branch, but could a new release be made by any chance?

**Comment by futuretap** [comment]
The last release is `2.14` from 09/2019 including the removal of `UIWebView`. Please check again.
