### ISSUE TITLE
Navigating back to IASK from e.g. a multi-value selection produces a warning

### ISSUE THREAD

**Issue by gereons** [futuretap/InAppSettingsKit#428]
Starting with iOS 13, reloading a `UITableView` that is not on-screen reports a warning

> UITableView was told to layout its visible cells and other contents without being in the view hierarchy

This happens when you navigate back to IASK's main tableview from eg. a multi-value selection, an easy fix seems to be to delay the reloading to the next runloop pass.

**Comment by futuretap** [comment]
Thanks, I fixed the issue in a different way using `reloadData`. In your PR the deselection animation was finished too soon when performing an interactive pop gesture.
