### ISSUE TITLE
Existing value not displayed / lost on open of List Groups child pane

### ISSUE THREAD

**Issue by jschneid** [futuretap/InAppSettingsKit#438]
**Steps to reproduce:**

1. Open the sample app, and run it. (I'm using iPhone 8, running in the simulator, as the target.)
2. In the running sample app, go to `Show Settings (Modal)` > `List groups` > `Add Tag...`
3. On the `Add Tag...` page, in the `Tag` field, enter a value (e.g. `abc`), then tap the `Done` button.
4. Back on the `List groups` page, observe that the new `abc` tag is present in the list. Tap it.

**Observed:**
 
- On the `Add Tag...` page displayed for the `abc` tag, the `Tag` field has no value -- it just displays the `Tag` placeholder value.
- If the Done button is tapped again (without re-entering the `abc` value), then back on the `List groups` page, the tag will show the default value of `Tag` instead of `abc`.

**Expected:**

- The existing item value (`abc`) should be initially populated into the `Tag` field when editing that existing item.

Reproduced on XCode 11.6 on OSX 10.15.6.

Is the behavior that I'm expecting above accurate?

**Comment by jschneid** [comment]
I tried testing this on other iOS versions today; the same behavior as described above was reproducible on simulators running on iOS versions 13.6, 12.4, 11.4, and 10.3.1.

**Comment by jschneid** [comment]
Is this project currently accepting pull requests?

**Comment by futuretap** [comment]
Thanks, should be fixed in 3.1.4.
