### ISSUE TITLE
PSRadioGroupSpecifier not working with List Groups

### ISSUE THREAD

**Issue by pcKanso** [futuretap/InAppSettingsKit#439]
When adding a PSRadioGroupSpecifier item to the Account.plist, selecting different items for different accounts does not work as expected. It always shows the same item selected for the different accounts (always picks the last selected item of PSRadioGroupSpecifier)

To repeat:

1) Copy a PSRadioGroupSpecifier from Fruit.plist and paste it into the Account.plist
2) Run sample app and go to the List Group example
3) Add accounts as needed and select different fruits for each account
4) Go back and verify different fruits are NOT selected for the different accounts

UPDATE: I did check this with a MultiValue lists (PSMultiValueSpecifier) item and that does work as expected so there is a workaround, although not ideal.

**Comment by pcKanso** [comment]
I determined that the cause of this problem was due to the settings store of the `IASKMultipleValueSelection` was not getting set when using list groups (`IASKListGroupSpecifier`).

I'm sure there is a better way as I don't know this code that well but these changes work for me so far:

1) IASKAppSettingsViewController.m

```
- (void)setSettingsStore:(id<IASKSettingsStore>)settingsStore {
	_settingsStore = settingsStore;
	_settingsReader.settingsStore = _settingsStore;
	
	// Workaround for PSRadioGroupSpecifier's in List Groups
	for (IASKMultipleValueSelection *selection in _selections) {
		if (![selection isEqual:[NSNull null]]) {
			selection.settingsStore = _settingsStore;
		}
	}
}
```

2) IASKMultipleValueSelection.h

Need to move `@property (nonatomic, strong) id<IASKSettingsStore> settingsStore;` to header file

3) IASKMultipleValueSelection.m

Add `[self updateCheckedItem];` to the end of `- (void)setSettingsStore:(id<IASKSettingsStore>)settingsStore` method.

Again, I'm sure there is a better way but these are the changes I made to get this to work properly.

**Comment by futuretap** [comment]
Thanks, I pulled your fix.
