### ISSUE TITLE
UIWebView and InAppSettingsKit

### ISSUE THREAD

**Issue by neilyoung** [futuretap/InAppSettingsKit#440]
I'm sorry if this question is already answered somewhere here, but I came across this, because my app, which used UIWebView, does no longer work on iOS 14. I switched over to WkWebView but found several references to UIWebView in InAppSettingsKit, which I love a lot.

Q1: Has InAppSettingsKit already removed away from UIWebVIew
Q2: I'm using   `pod 'InAppSettingsKit'` in my app. If 1) is true, what migration path would I have to consider and what version to include?

TIA

**Comment by futuretap** [comment]
Q1: Yes.
Q2: You should definitely update to the newest 3.x version (which is what you're doing by not specifying a version in the Podfile). When upgrading from 2.x there are a few changes in the delegate protocol (see the [release notes](https://github.com/futuretap/InAppSettingsKit/blob/master/RELEASE_NOTES.md)) but it should be quite straight forward to migrate your existing delegate code.

**Comment by neilyoung** [comment]
Thanks for the quick answer. I didn't do a pod update or pod install for a quite long time, so maybe it is time now

**Comment by neilyoung** [comment]
OK, updated 

Installing InAppSettingsKit 3.1.3 (was 2.10)

Now let's see what has been changed 👍

**Comment by neilyoung** [comment]
Could you please quickly help me? 

NotificationCenter.default.addObserver(self, selector: #selector(SettingsViewController.settingDidChange(_:)), name: NSNotification.Name(rawValue: kIASKAppSettingChanged), object: nil)

Cannot find 'kIASKAppSettingChanged' in scope

**Comment by futuretap** [comment]
Check the sample app's `MainViewController.swift` for reference:

    NotificationCenter.default.addObserver(self, selector: #selector(settingDidChange(notification:)), name: Notification.Name.IASKSettingChanged, object: nil)
