### ISSUE TITLE
Crashed when hiding single row in section

### ISSUE THREAD

**Issue by DemianSteelstone** [futuretap/InAppSettingsKit#442]
Hi!
I have something like this

PSToggleSwitchSpecifier
PSGroupSpecifier
PSToggleSwitchSpecifier

When toggling first switch I wanna to hide with animation group and another switch, but it crashes every time
 because of wrong indexPath

```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', 
reason: 'Attempted to perform update with invalid index path:
<NSIndexPath: 0x281963ce0> {length = 2, path = 1 - 18446744073709551615}'
```

**Comment by futuretap** [comment]
Please provide a sample app and we'll gladly look into it.

**Comment by DemianSteelstone** [comment]
Ah, my bad. This was the old version. After upgrading to 3.1.5 it seems to work fine
