### ISSUE TITLE
No entries is displayed on macOS

### ISSUE THREAD

**Issue by HubertZhang** [futuretap/InAppSettingsKit#444]
Because `IASKSpecifier.userInterfaceIdioms` does not contains `UIUserInterfaceIdiomMac`, all specifiers are filtered out in `IASKSettingsReader._reinterpretBundle` when running the application built by catalyst on macOS .

**Comment by futuretap** [comment]
Oops. Would love to get a pull request if you've the chance to fix it yourself. Not sure when I'll be able to take a look.
