### ISSUE TITLE
Done button did not work when following instructions

### ISSUE THREAD

**Issue by horseshoe7** [futuretap/InAppSettingsKit#446]
Love the idea of this framework.  Adoption of it really is hugely dependent on the Getting Started guide.  If this doesn't work, people lose faith in this.

I followed the integration instructions, set the Done button to ON, but when I pressed it at runtime, nothing happened.

Yes, it's modal.  Yes, it's embedded in a UINavigationController.  So I did everything you told me to but it doesn't work.

So the simplest case, getting started, does not work as advertised.

The fix should be:

> Via storyboard:
> 
> Drag and drop a Table View Controller embedded into a Navigation Controller into your app and wire the storyboard to your app UI
> Set the Table View Controller class to IASKAppSettingsViewController
> In the Table View Controller set "Show Done Button" under "App Settings View Controller" to "On" if you’re presenting the navigation controller modally.  If you do this, you will need to provide a delegate that responds to the method -settingsViewControllerDidEnd: and dismiss the view controller yourself.
> Set the Table View to "Grouped" style.

**Comment by futuretap** [comment]
Thanks for the recommendation. Fixed.

**Comment by horseshoe7** [comment]
wow that was fast!  Awesome.  Thanks.
