### ISSUE TITLE
Does not compile on ios versions < 14

### ISSUE THREAD

**Issue by jamesalvarez** [futuretap/InAppSettingsKit#448]
`@property (nonatomic, readonly) UIDatePickerStyle datePickerStyle API_AVAILABLE(ios(13.4));`

in IASKSpecifier.h

Causes build to fail as UIDatePickerStyle not available - I think you will need preprocessor to cut out this line not just API_AVAILABLE

**Comment by futuretap** [comment]
Just to understand, are you building on a legacy version of Xcode? 

We generally target the current stable version of Xcode, however, we do support deployment targets back to iOS 9.

**Comment by jamesalvarez** [comment]
Xcode 11.3.  I believe API_AVAILABLE just marks whether the declaration is available or not and produces warnings, but it never gets to that stage.  The issue is that the declaration includes a symbol that is not in that version of iOS, so whole declaration needs to be enclosed in suitable preprocessor to prevent it trying to compile.  I am trying to build for iOS version 11.

**Comment by futuretap** [comment]
Is there a particular reason why you don't use the current version of Xcode? Xcode 11.3 was even before iOS 13.4 IIRC.

**Comment by jamesalvarez** [comment]
Older macs cannot get the latest OS and therefore not the latest Xcode.
But actually I have latest on my work PC and I get same issue.

**Comment by futuretap** [comment]
Apple usually accepts builds for the App Store only from recent Xcode versions. That's why we generally don't bother supporting legacy Xcode versions.

In Xcode 12 I can't reproduce the issue. Can you please supply a sample project?

**Comment by jamesalvarez** [comment]
Apologies I was wrong about my work PC having latest - it does but it also has 11.3.  I have both versions and used wrong one!  Still, app store does still accept builds from 11.3 ( the maximum version for Mojave).  Obviously no need to submit project as it's just the cloned dir.
