### ISSUE TITLE
Which object should be passed when posting a kIASKAppSettingChanged notification?

### ISSUE THREAD

**Issue by JensDee** [futuretap/InAppSettingsKit#450]
It seems the object should be the view or the view controller the event is originating from, right?

In this case the key is referenced. Why?
https://github.com/futuretap/InAppSettingsKit/blob/266296ff2119b0a09a23ccfd3c28704e3d9384af/InAppSettingsKit/Controllers/IASKAppSettingsViewController.m#L1200

**Comment by futuretap** [comment]
It was a mistake. We simply didn't change it so far because some apps rely on the (wrong) behavior.
We'll change that – alongside a bold release note – in an upcoming version.

**Comment by JensDee** [comment]
Thanks for the explanation. I assumed that, but wanted to make sure. As I was updating some code, I noticed this inconsistency and was wondering what is the expected behaviour.

**Comment by futuretap** [comment]
Published 3.3 with a release note. Thanks for bringing this to attention!
