### ISSUE TITLE
How to set TableView to "Grouped" style using Interface Builder.

### ISSUE THREAD

**Issue by cyrussinc** [futuretap/InAppSettingsKit#452]
I'm reading the setup guide, and I can't seem to figure out how to do Grouped tableview style. Any help on this would be greatly appreciated:

![Screen Shot 2021-02-21 at 10 23 16 PM](https://user-images.githubusercontent.com/42503162/108670467-c770b900-7493-11eb-844d-e1d759ca6c53.png)

**Comment by futuretap** [comment]
See the last line: <img width="262" alt="image" src="https://user-images.githubusercontent.com/110374/108679133-5e695f80-74ec-11eb-8d6d-ea4f39f78c05.png">
