### ISSUE TITLE
Bad alignment for "compact" Date pickers

### ISSUE THREAD

**Issue by tipa** [futuretap/InAppSettingsKit#453]
See screenshot below. Compact date/time pickers should be aligned right.
Can be fixed by wrapping the date picker into a horizontal stack panel and set a constraint to the right cell border. ([idea taken from here](https://stackoverflow.com/a/65003725/3585218))

![Screenshot 2021-03-30 at 12 06 19](https://user-images.githubusercontent.com/2863198/112972242-58504980-9150-11eb-81ec-e0887ee529e5.png)

**Comment by futuretap** [comment]
You're right. Not sure when I'll find time to fix it. If you feel like fixing it yourself, I'd gladly accept a PR. 😉

**Comment by tipa** [comment]
I think the problem can be fixed by simply removing this line:
https://github.com/futuretap/InAppSettingsKit/blob/c1b81d7b87ee70b9e963d27e87cb092b80ae2b86/InAppSettingsKit/Views/IASKEmbeddedDatePickerViewCell.m#L23

That causes the date picker to align right.

**Comment by futuretap** [comment]
Removing that line would break the layout if the title is too long. We want a proper truncation in this case.
Should be solved in 3.3.1.

**Comment by tipa** [comment]
Awesome, thanks a lot for the quick fix!
