### ISSUE TITLE
InAppSettingsKit broken for SPM integrations on XCode 13-beta3

### ISSUE THREAD

**Issue by scannillo** [futuretap/InAppSettingsKit#456]
[In the XCode 13-beta3 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes), you can see this change was made to SPM:
> Linking Swift packages from application extension targets or watchOS applications no longer emits unresolvable warnings about linking to libraries not safe for use in application extensions. This means that code referencing APIs annotated as unavailable for use in app extensions must now themselves be annotated as unavailable for use in application extensions, in order to allow that code to be used in both apps and app extensions. (66928265)

My app pulls in InAppSettingsKit via SPM, and I cannot compile due to the following errors coming from the framework:

![Screen Shot 2021-07-21 at 10 11 45 AM](https://user-images.githubusercontent.com/35243507/126514796-8808bb45-ae50-4c13-9e3c-d40fa8838a71.png)

An SDK I work on had to also deal with this. You can check out [our PR](https://github.com/braintree/braintree_ios/pull/713) to see how we fixed it.

I am on version 3.1.8 of InAppSettingsKit.

**Comment by futuretap** [comment]
Thanks, should be fixed in 3.3.2.

**Comment by futuretap** [comment]
After cleaning derived data it looks like it is fixed indeed.

**Comment by scannillo** [comment]
Hello - thank you for getting this fix out so quickly! Much appreciated.
