### ISSUE TITLE
Date picker cell styling

### ISSUE THREAD

**Issue by tipa** [futuretap/InAppSettingsKit#461]
2 small problems:

1. When the system font size is changed, all cells properly scale their text, except the DatePicker cell
2. The "selectionStyle" of the cell is set not set to "None" when" DatePickerStyle" is set to "Compact".  

![Bildschirmfoto 2021-09-16 um 7 25 51 PM](https://user-images.githubusercontent.com/2863198/133657571-fd17a97e-11c0-4e61-b0f2-4bfd8a0da8f3.png)

**Comment by futuretap** [comment]
Fixed in 3.6.2.
