### ISSUE TITLE
Headers missing for Carthage framework

### ISSUE THREAD

**Issue by prashant-bhargava-hs** [futuretap/InAppSettingsKit#463]
Hi thanks for all your hard work on this!

It appears that with the latest restructuring, none of the header files (.h) are bundled for the Carthage framework anymore. We are using the latest release `3.3.5` and started facing this issue as soon as we pulled it in.

**Comment by diederich** [comment]
Oh noes, sorry about that! Will take a look soon. There's a little test helper for the Carthage setup, could probably add a line to check if the headers are part of the framework in the `XCFramework`.
