### ISSUE TITLE
FooterText not wrapping

### ISSUE THREAD

**Issue by CrewNerd** [futuretap/InAppSettingsKit#467]
I just upgraded from 3.0.1 to 3.3.5 and the only regression I've noticed is that my FooterText no longer line-wraps. It looks like vertical space is still being reserved as though the text would be wrapped, but it just runs off the end of the first line with an ellipsis.

Presumably, this impacts HeaderText as well, but I haven't checked this. I'm testing on iOS 15.1.

Update: further testing showed that the regression occurred between version 3.3.1 and 3.3.2.

**Comment by futuretap** [comment]
Only change from 3.3.1 to 3.3.2 was to allow `. insetGrouped` table view style, which should be purely additional. Can you provide a sample app reproducing the issue?

**Comment by CrewNerd** [comment]
Not easily, but with some experimenting, I tracked the regression down to the change in IASKAppSettingsViewController.m at line 916 in [this commit](https://github.com/futuretap/InAppSettingsKit/commit/28db3bdc62a216f53da1bfaff2466a8abd1b2d2f). If I revert that one change, my footer text wraps correctly.

**Comment by futuretap** [comment]
The problem is I can't reproduce the problem here. My footer text still wraps fine. And we need the change in that commit in order to support a non-plain UITableViewStyle in child panes (we want to create child panes with the same UITableViewStyle as the parent).

How do you integrate IASK? Which `UITableViewStyle` are you using?

**Comment by futuretap** [comment]
I'm afraid, we need a sample app to reproduce the problem.

**Comment by CrewNerd** [comment]
My root table style is Plain (the default). If I hack the code to force the child view style to be Grouped, then the footer text wraps properly in the new child view. So it looks like the problem occurs with FooterText when the style is Plain, but I don't think I can set that since the activation happens as part of the XIB loading.

**Comment by futuretap** [comment]
You should be able to set the table view to grouped in the storyboard.

**Comment by CrewNerd** [comment]
It's a XIB, though, not a storyboard. When the XIB loads, the view controller is initialized with initWithCoder. Shouldn't the default style be Grouped? If I tried to call initWithStyle with style=Plain, I'd get a warning, so that shouldn't be the default when loading a XIB.

**Comment by futuretap** [comment]
Shouldn't matter. Just set the style of the table view to grouped in IB.

**Comment by CrewNerd** [comment]
I'm not seeing all of the table view properties there. I don't see anywhere to set the table style in IB. The only properties I see are the three defined in IASKAppSettingsViewController.h (showDoneButton, neverShowPrivacySettings, and cellLayoutMarginsFollowReadableWidth)

**Comment by CrewNerd** [comment]
Properties from UIViewController are also settable in IB, but not for UITableViewController.

**Comment by futuretap** [comment]
You should have a UITableView object inside the UITableViewController.

**Comment by CrewNerd** [comment]
Not sure what you're getting at. Sure, there's a UITableView object there, but the style property is read-only and I can't get IB to show me that property. Here's what the property inspector looks like for the app settings view controller
<img width="347" alt="xcode" src="https://user-images.githubusercontent.com/65362/142700695-ffd1eb8f-a1ef-4a35-9981-b59af06465ae.png">
.

**Comment by futuretap** [comment]
I can set the style to Grouped:
<img width="951" alt="image" src="https://user-images.githubusercontent.com/110374/142703931-01d36513-79f2-416d-8df3-235d865420a9.png">

**Comment by CrewNerd** [comment]
Problem solved - I had to remove my IASKAppSettingsViewController from the hierarchy in IB and add it back again. Then, I finally got a table view in the tree that I could set properties on. Thanks for your help!
