### ISSUE TITLE
Release the fix done for Carthage headers

### ISSUE THREAD

**Issue by prashant-bhargava-hs** [futuretap/InAppSettingsKit#473]
Hi @diederich @futuretap  

🙌🏼  Many thanks for fixing the bug, https://github.com/futuretap/InAppSettingsKit/pull/465 however it has not been released yet.

Could this be released please as we are blocked from pulling in the latest stable updates ?  

Thanks!

**Comment by futuretap** [comment]
Released 3.3.6
