### ISSUE TITLE
Disable Multiline Text view

### ISSUE THREAD

**Issue by Wiwaltill** [futuretap/InAppSettingsKit#478]
It would be great if you could lock the input in your long text field. This would make it easier to display longer texts. 

It would be an alternative to the long footer text and could be set via UserDefaults.

**Comment by futuretap** [comment]
You mean an `IASKIsEditable` flag in the plist? Or something more dynamic using a delegate callback?

**Comment by futuretap** [comment]
You could subclass `IASKAppSettingsViewController` and override `-tableView:newCellForSpecifier:`:

```
- (UITableViewCell*)tableView:(UITableView *)tableView newCellForSpecifier:(IASKSpecifier*)specifier {
    UITableViewCell *cell = [super tableView:tableView newCellForSpecifier:specifier];
    if ([specifier.type isEqualToString:kIASKTextViewSpecifier]) {
        ((IASKTextViewCell*)cell).textView.editable = NO;
    }
    return cell;
}
```
