### ISSUE TITLE
When using IASKSegueIdentifier, the row is not deselected when closing the presented view controller

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#479]
When using `IASKSegueIdentifier`, the row is not deselected when closing the presented view controller.
This behaviour can be reproduced in the Sample app:

1. Launch the Sample app
2. On the first tab "Featured" select any of the 2 options
3. Scroll down to the section with "Open URL". 
4. There is a row named `Custom Subview (via Storyboard segue)`. Select it
5. When the modal view controller opens, swipe it down to close
6. Row named `Custom Subview (via Storyboard segue)` is still selected ❌:
<img width="564" alt="Screenshot 2023-01-17 at 16 53 50" src="https://user-images.githubusercontent.com/2139844/212946021-be6f50db-9a24-47ad-9a06-e6e37083b854.png">

**Solution**

`IASKAppSettingsViewController` should monitor for a rewind segue and deselect the row.

**Comment by funnel20** [comment]
I did some investigation here. 
The segue's viewcontroller will be presented modally. Hence any delegate methods, like `viewWillDisappear:` and `viewWillAppear:` will not be called when that viewcontroller is presented and dismissed. Consequently the selected indexPath is not deselected, since that is handled in `viewWillAppear:`.

An unwind segue has to be defined in the presenting view controller, and has to be initiated by the presented view controller when that is being dismissed. This is a bit complex to implement in IASK.

I came up with a pretty simple solution, where IASK starts monitoring whether the presented view controller by the segue is dismissed. This is done by a repeating timer (100 ms), that is started after the segue is presented.

Whenever the timer fires and the viewcontroller is no longer presented, the timer is stopped and the selected row deselected.
In code, the segue-related section of [`tableView:didSelectRowAtIndexPath:`](https://github.com/futuretap/InAppSettingsKit/blob/9e1643ca08fb6362abc9d31c066b5783e8bc0be2/Sources/InAppSettingsKit/Controllers/IASKAppSettingsViewController.m#L818) becomes:

```ObjC
		NSString *segueIdentifier = specifier.segueIdentifier;
        if (segueIdentifier) {
            @try {
                [self performSegueWithIdentifier:segueIdentifier
                                          sender:self];
                
                /*
                 NOTE: The segue's viewcontroller will be presented modally. Hence any delegate methods, like `viewWillDisappear:` and `viewWillAppear:` will not be called when that viewcontroller is presented and dismissed. Consequently the selected indexPath is not deselected, since that is handled in `viewWillAppear:`.
                 To resolve this, a repeating timer is used to check whether the presented view controller gets dismissed.
                 */
                self.checkSegueDismissedTimer = [NSTimer timerWithTimeInterval:0.1
                                                                       repeats:YES
                                                                         block:^(NSTimer * _Nonnull timer) {
                    // When dismissed:
                    if (self.presentedViewController == nil) {
                        // Deselect row:
                        [self.tableView deselectRowAtIndexPath:indexPath animated:YES];
                        
                        // Stop timer:
                        if ([self.checkSegueDismissedTimer isValid]) {
                            [self.checkSegueDismissedTimer invalidate];
                        }
                    }
                }];
                
                // Add timer to the Main runloop:
                [[NSRunLoop mainRunLoop] addTimer:self.checkSegueDismissedTimer
                                          forMode:NSRunLoopCommonModes];
            } @catch (NSException *exception) {
                NSLog(@"segue with identifier '%@' not defined", segueIdentifier);
                [tableView deselectRowAtIndexPath:indexPath animated:YES];
            }
            [tableView endUpdates];
            return;
        }
```

**Comment by futuretap** [comment]
Thanks @funnel20!
