### ISSUE TITLE
How to show Large Navigation Title

### ISSUE THREAD

**Issue by mixtly87** [futuretap/InAppSettingsKit#481]
When IASKAppSettingsViewController is displayed, it shows navigationBar title in collapsed form. When table view is manually scrolled to top, large navigation title is revealed.

I want to show large navigation title as soon as IASKAppSettingsViewController is shown. Can that be achived?

I tried various options like:

```
// Scroll to the top row
tableView.scrollToRow(at: IndexPath(row: 0, section: 0), at: .top, animated: true)

// Adjust the content inset to account for the height of the navigation bar
let topInset = navigationController?.navigationBar.frame.maxY ?? 0
tableView.contentInset = UIEdgeInsets(top: topInset, left: 0, bottom: 0, right: 0)
```
in `viewWillAppear` but none seem to work.

Does anyone have an idea how can this be achieved?

**Comment by futuretap** [comment]
Just set `navigationItem.largeTitleDisplayMode` of your root `IASKAppSettingsViewController` to automatic or always.
