### ISSUE TITLE
have not enter greater than 255 character

### ISSUE THREAD

**Issue by hoangde2811** [futuretap/InAppSettingsKit#491]
Hi developer!
I have cast IASKPSTextFieldSpecifierViewCell to delegate textField, my code below
if let indexPath = settingsViewController.settingsReader?.indexPath(forKey: "field_display_name") {
                let viewCell = settingsViewController.tableView.cellForRow(at: indexPath) as? IASKPSTextFieldSpecifierViewCell
                viewCell?.textField.delegate = self
            }
I was listened UITextFieldDelegate or UITextViewDelegate but it don't unavailable. Help me.
Sincerely thank you.

**Comment by futuretap** [comment]
It's not clear what you did exactly. Please provide a sample project.

**Comment by hoangde2811** [comment]
Hi developer!
I use PSTextFieldSpecifier to user name change and i want if user enter
 greater than 255 character then user can't enter anymore. Help me.
Sincerely thanks

**Comment by futuretap** [comment]
I understand. Please post a sample project so we can check what's going on.
