### ISSUE TITLE
Sample app doesn't run in Xcode 15.4 (or due to lack of docu I'm clueless how to run it)

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#501]
When I checkout the project from Github and open the sample app in Xcode, it doesn't compile.

Steps to reproduce:

1. In Finder, from folder "InAppSettingsKitSampleApp", open "IASKSampleApp.xcodeproj"
2. In Xcode, select a simulator and Run
3. A bunch of errors are shown:
<img width="990" alt="Screenshot 2024-09-20 at 20 39 34" src="https://github.com/user-attachments/assets/ad59038e-1f79-46bd-a21f-ddab9891a8df">

Questions:

1. Is this the correct approach to use the Sample app? E.g. did I open the correct Xcode project from  folder "InAppSettingsKitSampleApp", since there are multiple? 
2. Based on question 1; would it be possible to add a section to the docu on how to use the Sample App?

**Comment by futuretap** [comment]
You should open the .xcworkspace instead and select the "Sample App" scheme.

**Comment by funnel20** [comment]
I have created PR https://github.com/futuretap/InAppSettingsKit/pull/503 to add a docu section for the Sample app.
