### ISSUE TITLE
`WKWebView` in `IASKAppSettingsWebViewController` does not respect the Safe Area; it shows content behind the dynamic island

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#502]
When lading an URL, like https://www.apple.com, part of the webpage is shown behind the dynamic island and behind the navigation bar:
![Simulator Screenshot - iPhone 15 Pro - 2024-09-20 at 20 46 10](https://github.com/user-attachments/assets/436d020f-48dd-4344-ab9b-cfd4c4347d34)

*.plist content:

<img width="527" alt="Screenshot 2024-09-20 at 20 46 49" src="https://github.com/user-attachments/assets/a9d8d8ad-1886-4aa7-81ec-68089a1c6cf1">

**Comment by funnel20** [comment]
As a work-around, I build my own `UIViewController` with:
* a `WKWebView`
* a `UIProgressView`
* dynamic `UIBarButtonItem`s for back and forward (meaning buttons are enabled/disabled whenever navigation is possible)
* option to show it full screen over the tab bar

![Simulator Screenshot - iPhone 15 Pro - 2024-09-27 at 11 01 25](https://github.com/user-attachments/assets/5809d11a-5208-459f-a312-1622ac01ba1d)

@futuretap If you're interested in this `WKWebView` with more options, please let me know. Then I can either help you to extend the existing `IASKAppSettingsWebViewController` or add mine to the project.

**Comment by futuretap** [comment]
I confirm the issue when loading https://www.apple.com. However, the problem does not occur for most other websites. Did you dig deeper what causes the issue?

In any case, I'd be more than happy to accept your help to fix `IASKAppSettingsWebViewController`. Having more options like a progress view and navigational buttons (back/forward/reload) would be useful. Unfortunately, the current calling mechanism using `IASKViewControllerClass` and `IASKViewControllerSelector` doesn’t really allow to specify parameters. I could imagine to introduce a dedicated `IASKURL` parameter for `PSChildPaneSpecifier` that directly opens a `IASKAppSettingsWebViewController`. Then we could add more boolean parameters like `IASKWebViewShowProgress` and `IASKWebViewShowNavigationalButtons`. What do you think?

**Comment by funnel20** [comment]
The websites that I use did show the issue. For the issue report, I randomly picked Apple website, which also shows the issue. So for me that was reproducible enough. I didn't dig any deeper, but I suspect it is related to not properly respecting the safe layout margins.

Because I didn't want to expose the used URLs to the app user, I couldn't use `SFSafariViewController`. Hence I decided to built my own `UIViewController` around a `WKWebView`.

I was pleasantly surprised that  I could use additional custom parameters using `IASKViewControllerClass` and `IASKViewControllerSelector`. So I specified a custom parameter `url` in the *.plist:

<img width="446" alt="Screenshot 2024-09-27 at 11 58 09" src="https://github.com/user-attachments/assets/0aa53296-0a0e-4487-962b-7605666200d7">

And I can retrieve it in `initWithFile:specifier:` via `specifier.specifierDict`:

```ObjC
@implementation WebViewController

- (id)initWithFile:(NSString*)file specifier:(IASKSpecifier*)specifier {
    NSLog(@"urlString: %@", file);
    NSLog(@"specifier: %@", specifier);
    
    // Get additional properties from *.plist:
    if ((self = [super init])) {
        _url = [NSURL URLWithString:NSLocalizedString([specifier.specifierDict valueForKey:@"url"], nil)];
    }
    return self;
}
```

**Comment by futuretap** [comment]
Indeed, you can access the specifier to get the parameters. I forgot. So it’s probably fine to just extend `IASKAppSettingsWebViewController`. Using a XIB based approach is not ideal for a package/framework. Could you migrate it to code and integrate it into the existing code?

**Comment by funnel20** [comment]
@futuretap Yes, I'm happy to extend `IASKAppSettingsWebViewController` programmatically with constraints.
As mentioned I'd like to add new `IASK...` parameters (the 4th was not named yet):

1. `IASKURL` [string] - the URL to load
2. `IASKWebViewShowProgress` [bool] - show a progress bar at the top of the `WKWebView`
3. `IASKWebViewShowNavigationalButtons` [bool] - show dynamic back and forward buttons at the right side of the `UINavigationItem`
4. `IASKWebViewHideBottomBar` [bool] - hide the toolbar at the bottom of the screen when the `IASKAppSettingsWebViewController` is pushed on to a navigation controller

For the 3 booleans, what should be the default value, when NOT specified in the *.plist?  
I suggest to disable all, so when users update IASK, they will get the same look and feel as the current code of `IASKAppSettingsWebViewController`. They can add the parameters to their *.plist to get the new features.

Do you agree?

**Comment by funnel20** [comment]
Current code uses very old style code, which is unaware of Safe Area:
```ObjC
self.webView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
```
I've replaced this by 4 proper anchor constraints to the `safeAreaLayoutGuide` and that resolves the main issue ✅

![Simulator Screenshot - iPhone 15 Pro - 2024-09-27 at 16 24 15](https://github.com/user-attachments/assets/f09ce73a-ae3d-4c4e-a206-27119f6c4f7e)

**Comment by funnel20** [comment]
Created new issue #504 because that's a feature request, while this issue relates to a bug.

**Comment by funnel20** [comment]
@futuretap PR #505 is ready to resolve this bug(s)

**Comment by futuretap** [comment]
Thanks, I agree with all your suggestions!
