### ISSUE TITLE
Extend `IASKAppSettingsWebViewController` with 3 new optional features; progress bar, navigational buttons and hide bottom bar

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#504]
As discussed in https://github.com/futuretap/InAppSettingsKit/issues/502#issuecomment-2378805894 : 

Extend `IASKAppSettingsWebViewController` programmatically with constraints.
Add new `IASK...` parameters:

1. ~~`IASKURL` [string] - the URL to load.~~ This is a redundancy of existing `File`
2. `IASKWebViewShowProgress` [bool] - show a progress bar at the top of the `WKWebView`
3. `IASKWebViewShowNavigationalButtons` [bool] - show dynamic back and forward buttons at the right side of the `UINavigationItem`
4. `IASKWebViewHideBottomBar` [bool] - hide the toolbar at the bottom of the screen when the `IASKAppSettingsWebViewController` is pushed on to a navigation controller

The 3 booleans, will be set default to `NO` when NOT specified in the *.plist, to get the same look and feel as the current code of `IASKAppSettingsWebViewController`.
When users want to get the new features, they can add the parameters to their *.plist.

#### Preview with all 3 features enabled

![Simulator Screenshot - iPhone 15 Pro - 2024-09-27 at 11 01 25](https://github.com/user-attachments/assets/5809d11a-5208-459f-a312-1622ac01ba1d)

**Comment by futuretap** [comment]
Thanks, as discussed in #502, let’s keep `File` instead of `IASKURL`.

**Comment by funnel20** [comment]
> Thanks, as discussed in #502, let’s keep `File` instead of `IASKURL`.

Changed requirements accordingly

**Comment by funnel20** [comment]
Added all 3 parameters with examples:

![Simulator Screenshot - iPhone 15 Pro - 2024-09-28 at 12 14 59](https://github.com/user-attachments/assets/e4457577-2827-4d4a-8bb3-d021caea62d6)

The full options view is like:

![Simulator Screenshot - iPhone 15 Pro - 2024-09-28 at 12 18 03](https://github.com/user-attachments/assets/564d71da-0023-4155-8e97-fe12a5c490cd)

Also verified on iPad 10th gen Simulator
