### ISSUE TITLE
Make property `File` (which represents the URL) from `IASKAppSettingsWebViewController` localizable 

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#510]
While migrating my apps to InAppSettingsKit 3.8.3 with the [latest changes](https://github.com/futuretap/InAppSettingsKit/issues/504) to `IASKAppSettingsWebViewController`, I stumble to a localization issue:

For an instance I use a localised URL from the *.strings files.
My custom WebViewController did handle this well by using `NSLocalizedString()`:
```ObjC
_url = [NSURL URLWithString:NSLocalizedString([specifier.specifierDict valueForKey:@"url"], nil)];
```

However, IASKAppSettingsWebViewController crashes at:
https://github.com/futuretap/InAppSettingsKit/blob/b6d44e1235d35c6bfb95b884b1e8975718f16ef9/Sources/InAppSettingsKit/Controllers/IASKAppSettingsViewController.m#L895

when `specifier.file` is no valid URL, but a localization string (e.g. `loginUrl`).

**Comment by funnel20** [comment]
@futuretap PR #511 is ready

**Comment by futuretap** [comment]
Thanks, merged.
