### ISSUE TITLE
`IASKAppSettingsWebViewController` opens Safari and leaves the app

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#512]
While migrating my apps to InAppSettingsKit 3.8.3 with the [latest changes](https://github.com/futuretap/InAppSettingsKit/issues/504) to `IASKAppSettingsWebViewController`, I stumble to an issue:

I have embedded Google Translate in the URL to translate the original webpage.
For example to translate https://www.apple.com into Dutch, I use URL https://www-apple-com.translate.goog/?_x_tr_sl=en&_x_tr_tl=nl&_x_tr_hl=en&_x_tr_pto=wapp as property `File` for `IASKAppSettingsWebViewController`.

When the page starts loading in `IASKAppSettingsWebViewController`, all of sudden the app is moved to background and Safari is brought to the foreground, which starts loading the URL. ❌

I don't want to reveal the URL to the user, nor leave the app. ❌

### Analysis
I have derived this behaviour to the following lines of code in `webView:decidePolicyForNavigationAction:decisionHandler:` of _IASKAppSettingsWebViewController.m_:
https://github.com/futuretap/InAppSettingsKit/blob/b6d44e1235d35c6bfb95b884b1e8975718f16ef9/Sources/InAppSettingsKit/Controllers/IASKAppSettingsWebViewController.m#L336-L344

Apparently when the `host` changes (between Google and Apple in the above example) during a redirect, this code decides to load the new host in Safari.

@futuretap Any idea why this logic is in?

**Comment by futuretap** [comment]
This is based on the idea that for your own host, you can control the web content. For third party websites, you don’t, so it makes sense to pass it to Safari. We also want to pass non http/https (e.g. app-specific) schemes to the system.

There are probably many different use cases which require different handling. I suggest to subclass `IASKAppSettingsWebViewController` and override the delegate callback.

**Comment by funnel20** [comment]
I do understand the non http/https (e.g. app-specific) schemes.
However, I'm puzzled by the redirects (also undocumented). When I want to open een URL in Safari, as a developer I will use `SFSafariViewController` in my code or `[UIApplication.sharedApplication openURL:]`.

However, when I decide to use `IASKAppSettingsWebViewController`, it's a deliberate choice to provide an **uninterrupted** in-app browser to the user.

The current logic makes it a lottery when the user stays in the app, or that Safari is opened.
I'm currently opening an URL to a manual of a manufacture in `IASKAppSettingsWebViewController`. After loading, it moves to Safari, because there is a redirect to a cookie consent popup:
![Simulator Screenshot - iPhone 15 Pro - 2024-10-28 at 09 19 04](https://github.com/user-attachments/assets/18cff266-cfc6-448e-bae3-f7349390b445)

This makes `IASKAppSettingsWebViewController` totally useless.

Especially after all my [changes and new options](https://github.com/futuretap/InAppSettingsKit/issues/504), like `IASKWebViewShowNavigationalButtons`, `IASKAppSettingsWebViewController` acts as a full in-app browser, where the user can navigate back.

Instead of subclassing, I'd propose to add a new boolean option `IASKWebViewAlwaysOpenInline`, which will bypass `[UIApplication.sharedApplication openURL:]` and forces to stay in the app.

Please let me know if you agree, so I can create this.

**Comment by futuretap** [comment]
You’ve convinced me that the current behavior is unexpected, undocumented and potentially problematic in many cases. Can you provide a PR that only checks for the scheme (https/http => in app, otherwise `-openURL:`)?

**Comment by funnel20** [comment]
@futuretap Sure, I'm happy to contribute. Especially by avoiding unexpected or even problematic behaviour. My time is a bit limited this week, but I'll do my best to find a moment.

**Comment by funnel20** [comment]
@futuretap It appeared a very simple fix, PR is ready at #514

**Comment by futuretap** [comment]
Thanks, merged in version 3.8.4.

**Comment by funnel20** [comment]
I have just upgraded IASK to 3.8.4 in one of my production apps. This works awesome now 👍
However, I noticed a need for a new feature, see: https://github.com/futuretap/InAppSettingsKit/issues/515
