### ISSUE TITLE
Breaking change in version 3.8.1: Hideous use of `tintColor` for multi-value cells breaks all similarity with native iOS Settings app

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#513]
When upgrading from version 3.7.0 to 3.8.3, all multi-value cells show the value in blue, instead of light grey:

![Simulator Screenshot - iPhone 15 Pro - 2024-10-28 at 10 05 26](https://github.com/user-attachments/assets/e1e8bce5-0db8-4b6c-803e-13b06838d9b2)

This breaks all similarity and consistency with the native iOS Settings app ❌:
![Simulator Screenshot - iPhone 15 Pro - 2024-10-28 at 10 06 18](https://github.com/user-attachments/assets/dade3a7c-2511-44f5-95d9-aa0d1eba3ac1)

### Questions

1. How to get rid of this blue color?
2. Why is a new feature automatically applied when updating to a newer version, which was in the [semver](https://semver.org) definition only a [Patch](https://semver.org/#spec-item-6) (3.8 **.1**)?
   >  Patch version Z (x.y.Z | x > 0) MUST be incremented if only backward compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.

**Comment by futuretap** [comment]
You’re right that such a change should not be made in a minor version update.

I still think that the change makes use of tint color more consistent by tinting all user-editable options. The gray color could be misinterpreted as disabled.

So how should we solve this?
- Go back to the system style
- Keep the current style
- Add an option (`IASKColorScheme` with `system` and `consistent` with which default?)

I'm open to feedback!

**Comment by funnel20** [comment]
@futuretap From the introduction on the README:

> InAppSettingsKit takes advantage of the same bundle and allows you to present the same settings screen within your app. So the user has the choice where to change the settings.

> IASK not only replicates the feature set of system settings but supports a large number of additional elements and configuration options.

The main idea behind your library, seems to **replicate the native iOS Settings app**.
I've installed the latest developer beta of iOS 18.1 onto on of my iPhones, it still shows the **grey color** for the selected multi-value:

![IMG_D3CBF77DB4A5-1](https://github.com/user-attachments/assets/2a62dc2d-5680-4b6d-950f-239f8b575c87)

This means that users are totally familiar with the grey color for many years, no risk of misinterpretation.

So in my opinion the correct workflow is:

1. Undo the tint changes and revert back to the system style to comply to the Readme and mimic iOS style. This can even be in a patch version 3.8.4 as soon as possible to prevent frustrating other developers that might update IASK.
2. If you like other styles, (like the current tinted), add a new optional parameter (e.g. `IASKColorScheme`). Important to:
  a. Never apply the option automatically, when developers migrate to the latest version. So when the option is enabled, always default it to the current familiar style, e.g. `system`.
  b. Use intuitive option names. E.g. `consistent` is too vague. `tinted` might be an option, but is still not clear, as I have no idea where I define the tint color. Is that a setting inside IASK, or from my SettingsViewController, or app theme, etc?
  c. That brings me by the most obvious constraint; provide proper documentation about the new feature. When the requirements are crystal clear, often option/parameter names originate naturally.

**Comment by futuretap** [comment]
Thanks for the feedback, I hope we get some from other users, too. Regarding your question: You can set `tintColor` on your initial IASKAppSettingsViewController’s `view`. That tintColor is propagated to all IASK child view controllers.

**Comment by triplef** [comment]
Are there any examples of other (system?) apps that use tinting in similar kinds of views?

While I like the idea of tinting to make it explicit that a UI element is tappable, I think the chevron already conveys this in list views and I'd probably also go with consistency with system UI here.

**Comment by funnel20** [comment]
Apple is quite consistent with the values at the right site of a tableview row; it's always grey and as @triplef mentions contains the familiar chevron. This can be seen in native iOS apps, such as:
* Photos. The tab bar uses blue tintcolor, tab "Albums: shows the grey values
* Health: Same; blue tab bar, tab "Data" shows for any Body measuremetn -> all data grey values and chevron
* Watch app; similar to Settings app
* Find My; same blue tab bar, tab "me" shows grey values with chevron
* Clock: yellow tint color on tab bar, tab "Timers" shows light grey value (since main theme is dark, and titles are white) with chevron

Summary: the tint color of the tab bar is **never** used for multi-select value.

**Comment by futuretap** [comment]
Thanks for the additional feedback with more system app examples. I think it makes sense to go back to the old behavior as a default. I added a `colorScheme` property to `IASKAppSettingsViewController` that allows to switch to the "tinted" (imo more consistent) scheme.

I also made sure, date picker supports the colorScheme. It was tinted before.

**Comment by funnel20** [comment]
@futuretap Awesome, I expect this is a good decision. Probably it's a good habit of adding the new `colorScheme` property to the documentation.
