### ISSUE TITLE
Extend `IASKAppSettingsWebViewController` with data detectors to recognise links, addresses, phone numbers, etc.

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#515]
I have upgraded IASK from version 3.8.0 to 3.8.4 in one of my production apps.
It contained a self made WebViewController with a XIB file with a `WkWebView` in the storyboard.

This has now been replaced by `IASKAppSettingsWebViewController` and I noticed a difference:

`WkWebView` shows hyperlinks at street address and phone numbers ✅:

![Simulator Screenshot - iPhone 15 Pro - 2024-11-04 at 09 42 58](https://github.com/user-attachments/assets/fb6c16b0-f0db-46de-b3d4-fce8713d01e5)

`IASKAppSettingsWebViewController` does not ❌:

![Simulator Screenshot - iPhone 15 Pro - 2024-11-04 at 09 42 53](https://github.com/user-attachments/assets/778d2df5-1f70-4113-8b57-e9d14b314a65)

It appears that it occurs in [`WkWebView`](https://developer.apple.com/documentation/webkit/wkwebview?language=objc), since the [`dataDetectorTypes`](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/1641937-datadetectortypes?language=objc) property of [`WKWebViewConfiguration`](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration?language=objc) is by default set to [`WKDataDetectorTypeAll`](https://developer.apple.com/documentation/webkit/wkdatadetectortypes/wkdatadetectortypeall?language=objc) in the Storyboard file:

<img width="258" alt="Screenshot 2024-11-04 at 09 51 40" src="https://github.com/user-attachments/assets/483443b1-6f7f-47d3-a32d-18e1ab451a7b">

Although this is no bug at all, we could easily extend `IASKAppSettingsWebViewController` with a new feature where these data detector(s) to assist users with convenient navigation. Especially since these links will be [handled by system apps](https://github.com/futuretap/InAppSettingsKit/issues/512).

@futuretap The question is whether you want to add this feature or not. And if so, how to implement it?
I'd like to propose 3 suggestions:

1. Implement all datadetectors by default for `IASKAppSettingsWebViewController`
2. Add a boolean option to the the plist configuration of `IASKAppSettingsWebViewController`, which switches between no data detectors (default) and all data detectors.
3. Add an option to the plist configuration of `IASKAppSettingsWebViewController` where multiple detector types can be added, defaults to [`WKDataDetectorTypeNone`](https://developer.apple.com/documentation/webkit/wkdatadetectortypes/wkdatadetectortypenone?language=objc).

I would prefer option 1, since I can't think of a use-case where I should disable these user-oriented conveniences. And also since this is the default `WkWebView` configuration when adding it to a view in Xcode. 
But maybe we can ask other IASK users for advice?

**Comment by futuretap** [comment]
I agree we should implement option 1 with all data detectors enabled. If users don’t want that, they should subclass `IASKAppSettingsWebViewController`.

**Comment by funnel20** [comment]
@futuretap Awesome, I'm working on a PR.

**Comment by funnel20** [comment]
While adding a `WKWebViewConfiguration` to `loadView` of `IASKAppSettingsWebViewController`, the sample app crashes with **EXC_BAD_ACCESS** when selecting the WebView.

Searching for this leads to https://stackoverflow.com/a/53939210/2439941, where it appears that creating the web view should be postponed to `viewDidLoad` instead of `loadView`.

I've renamed `loadView` to `viewDidLoad` and of course called `[super viewDidLoad]`.
Indeed the crash is prevented, and the web view loads properly.

I was not aware of `loadView` at all, since I always use with NIB-files or Storyboard.
After having read the Apple docu of [`loadView`](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621454-loadview), it becomes clear to me that it only creates the view.
And consequently:

> If you want to perform any additional initialization of your views, do so in the [viewDidLoad()](https://developer.apple.com/documentation/uikit/uiviewcontroller/1621495-viewdidload) method.

The [current code](https://github.com/funnel20/InAppSettingsKit/blob/5c1eab86b07c8c09dd9be006bb799ab6f3d9fc4b/Sources/InAppSettingsKit/Controllers/IASKAppSettingsWebViewController.m#L58-L180) of `loadView` already contains quite some additional initialization, which didn't crash yet. Basically according to this Apple docu quote, it should be moved to `loadView`. 

@futuretap How do you want to approach this?

1. Just rename `loadView` to `viewDidLoad`, as it seems to work.
2. Add `viewDidLoad` and move appropriate code sections from `loadView` to it.

**Comment by funnel20** [comment]
> I agree we should implement option 1 with all data detectors enabled. If users don’t want that, they should subclass `IASKAppSettingsWebViewController`.

The data detectors are just 1 example of [WKWebViewConfiguration](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration?language=objc), or `WKWebView` properties, that are enabled by default when adding a `WKWebView` to Interface Builder. E.g.:

- Display: Link Preview
- JavaScript: Enabled
- Media: Picture-in-Picture

<img width="258" alt="Screenshot 2024-11-04 at 11 56 47" src="https://github.com/user-attachments/assets/6df573dd-ba08-4f7b-af65-34e2c2651d9d">

@futuretap What do we want to do with all these properties?

**Comment by futuretap** [comment]
Regarding `-loadView` vs. `-viewDidLoad`, we should keep both. `-loadView` should create the views, `-viewDidLoad` should do the web view configuration as this seems to only work there.

I suggest to enable all properties except "Can Auto-open Windows".

**Comment by funnel20** [comment]
@futuretap Ok, will move specific `WKWebView` configuration to `viewDidLoad`.

To have mutual understanding on properties, what do you mean with "enable all properties"?

- All possible options that `WKWebView` and `WKWebViewConfiguration` have, based on the docu of them (it are a lot)
- From the above screenshot of Interface Builder: the **entire** set of options all enabled (e.g. "Media: Inline Playback")
- From the screenshot of Interface Builder: the set of options that are selected **by default** in Xcode (e.g. "Media: Airplay")

**Comment by futuretap** [comment]
I suggested the second option. Let’s use a reasonable default configuration. We could design it subclass friendly by implementing and calling a `-configureWebView` method that can be easily overridden.

**Comment by funnel20** [comment]
@futuretap Forgive me if I keep asking annoying questions, but the Requirement Management is always the hardest part.
The second option contradicts with your [previous remark](https://github.com/futuretap/InAppSettingsKit/issues/515#issuecomment-2455453506):

> I suggest to enable all properties except "Can Auto-open Windows".

Is it still option 2, or option 2 except "Can Auto-open Windows"?

For the subclass feature, I prefer to create another issue, so we can focus on single tasks. Is that ok?

**Comment by futuretap** [comment]
> Is it still option 2, or option 2 except "Can Auto-open Windows"?

Option 2 except "Can Auto-open Windows".

Feel free to create another issue for subclassing.

**Comment by funnel20** [comment]
@futuretap I still have some questions about option 2, after reading the iOS docu.
For instances the 2 checkboxes at "Interaction: for Audio/Video Playback" refers to property [`mediaTypesRequiringUserActionForPlayback`](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration/1851524-mediatypesrequiringuseractionfor?language=objc), where we define the media types that require a user gesture to begin playing.
The Apple default in Xcode with both checkboxes disabled, means `WKAudiovisualMediaTypeNone`.
When you want to enable them both, it means that auto-start of both video and audio is disabled, and the users needs to make a gesture to start it.
Is this really what you want? I prefer option 3, where Apple somehow made some user-oriented considerations of the default values in Xcode.

**Comment by futuretap** [comment]
Of course you’re right, I agree. I'm confident you’ll choose a sensible configuration that makes sense for most IASK users!

**Comment by funnel20** [comment]
@futuretap This is the set that I came up with:

https://github.com/funnel20/InAppSettingsKit/blob/ab1689e19ac975529fc0304dc9e1913f9917a6bb/Sources/InAppSettingsKit/Controllers/IASKAppSettingsWebViewController.m#L151-L176

It has been validated on several pages, to check the data detectors and media behaviour.

Please review and let me know any desired changes, or if I can mage a PR.

**Comment by futuretap** [comment]
Looks good, thanks. Let’s just extract the web view configuration into a separate method that is included in the .h file, for easy overriding.

**Comment by funnel20** [comment]
Unfortunately `configuration` is read-only. It can only be assigned as initialiser of WKWebView via:
```ObjC
self.webView = [[WKWebView alloc] initWithFrame:CGRectZero configuration:configuration];
```

So we should assign a method to the .h file, that's why I wanted to open a new ticket for that.

**Comment by futuretap** [comment]
That’s why I propose to extract the whole code to assign a config to the web view into a `-configureWebView` method.

**Comment by funnel20** [comment]
@futuretap Forgive me my stupidity, but how would an IASK user call `configureWebView:` on `IASKAppSettingsWebViewController`? Can you provide a code sample, so I can use that to test this functionality?

Background: I'm not a pro in subclassing or other complicated tricks. Especially when I turn off my developer hat and put on my user hat, as a user of 3rd party libs I prefer simplicity and ease of use.

An alternative to a method `configureWebView:` is a property like `webViewConfiguration`, where we catch the setter in the *.m file, and re-init the webView upon that event. In that way the user can also read the existing configuration from the property and modify it according to its needs.

**Comment by futuretap** [comment]
A user would create a subclass of IASKAppSettingsWebViewController and override the  `-configureWebView:` method. Then, the subclass name would be referenced by `IASKViewControllerClass` in the settings plist. To allow calling `super` from the subclass it’s required to publish the method signature in the .h file.  Does that make sense?

**Comment by funnel20** [comment]
Still not clear to me. Let's say a user wants to disable JavaScript.
In other words he needs to change the `configuration` property (which is read-only) of `webView` by changing:

```ObjC
configuration.defaultWebpagePreferences.allowsContentJavaScript = NO;
```

How should he do this in this proposed override method and how will that be effectuated inside the *.m file?

**Comment by futuretap** [comment]
The user would then copy the original implementation of `-configureWebView:` into the subclass and modify just the needed properties. Then, the call to `super` is not needed. In the code above, I mixed .h and .m (`@interface` into .h, `@implementation` into .m).

**Comment by funnel20** [comment]
I don't know the opinion from other programmers. But in my 15 year of iOS programming I have never ever done this.
For 1 simple reason; **maintainability**:

In theory; every time a user would update IASK, he should remember to verify the original implementation of `-configureWebView:` by copying it from the *.m file, redo the customisation in the subclass and do validations.

To me, this is an unacceptable and unreliable workflow, where the risks are larger than the benefits. In other words; bad practise.

Can't we just add a property to `IASKAppSettingsViewController`, like existing `showDoneButton` or `showCreditsFooter`, which we propagate somehow to `IASKAppSettingsWebViewController` to update the webView configuration?

**Comment by futuretap** [comment]
This doesn’t work because the web view controller is dynamically allocated and `IASKAppSettingsViewController` doesn‘t even know that the allocated view controller is a web view controller.

What we could do: instead of a `-configureWebView:` method we could have a `webViewConfiguration` readonly property that the user can override. I‘m much in favor of a subclassing approach because it is more flexible.

**Comment by funnel20** [comment]
It's your project. I've done what is in my power to contribute, but this is out of my territory.

For the sake of resolving bug #516 for IASK users (that I introduced), I suggest to make a release 3.8.5 **today**. 
Preferably you also release the changes I've made for this one (#515) when I provide a PR.
Because that will add more well-thought settings to the webView as in the current public release.

Then we create a new issue about customisation of the webview and we have time to discuss that, or you do it yourself.

**Comment by futuretap** [comment]
Thanks, merged as 3.8.5. I've moved the web view config into a readonly property that can be overridden if needed.

**Comment by funnel20** [comment]
@futuretap Awesome, I've updated to 3.8.5 in the production app from the issue description, now the street address and phone numbers are links ✅

Please **note** that at https://github.com/futuretap/InAppSettingsKit/releases version 3.8.4 still has the badge "Latest".

**Comment by futuretap** [comment]
Maybe a caching issue. I did set the checkbox to indicate the latest release.

**Comment by funnel20** [comment]
@futuretap Now the label is correct. Thanks for double-checking
