### ISSUE TITLE
The sample app shows an empty web view when selecting "WebView" or "WebView without tab bar (when pushed)"

### ISSUE THREAD

**Issue by funnel20** [futuretap/InAppSettingsKit#516]
While working on a PR for #515 , I noticed that the sample app in version 3.8.4 doesn't load a webpage, the canvas stays empty when selecting "WebView" or "WebView without tab bar (when pushed)" ❌:

![Simulator Screenshot - iPhone 15 Pro - 2024-11-04 at 10 38 43](https://github.com/user-attachments/assets/9f20d868-6b53-4189-8508-c65014c518e1)

Other options, such as "WebView with progress bar" do load the page ✅:

![Simulator Screenshot - iPhone 15 Pro - 2024-11-04 at 10 39 19](https://github.com/user-attachments/assets/642c28fb-316d-403c-8391-ed07cfbd8ae9)

Based on the difference in page title in the navigation bar, 2 different resources are used:

- File _settings_about.html_
- URL https://www.futuretap.com

Why is the HTML file not loading anymore?
Might be related to changes of https://github.com/futuretap/InAppSettingsKit/issues/512

**Comment by futuretap** [comment]
Indeed, we should include `file` to the list of locally handled URL schemes!

**Comment by funnel20** [comment]
@futuretap oops, my bad

**Comment by futuretap** [comment]
Thanks, merged as 3.8.5.
