### ISSUE TITLE
Merging custom cell and controller class customization from fork

### ISSUE THREAD

**Issue by evadne** [futuretap/InAppSettingsKit#59]
In [my fork](http://github.com/iridia/InAppSettingsKit), there is a partial implementation that allows one to override classes used for the switch, the cells and the table view controller, so it’s possible to create customized UI.

Currently, I’ve placed properties on the settings view controller that get assigned to classes of various cells, which is used to create them when appropriate.  I’ve also re-factored the project a bit, so it is possible to create custom UIControl classes that work like UISwitch, but are not descendants of UISwitch, to allow customized switches.  For example, SSSwitch from SSToolkit is used in one of my projects.

I can then do this in a `IASKAppSettingsViewController` subclass:

```
self.specifierViewControllerClass = [TASettingsSpecifierViewController class];
self.switchSpecifierCellClass = [TASettingsToggleSwitchSpecifierViewCell class];
self.sliderSpecifierCellClass = [TASettingsSliderSpecifierViewCell class];
```

Because `UISwitch` is changed to `UIControl<IASKSwitchCustomizing>` in `IASKPSToggleSwitchSpecifierViewCell`, `TASettingsToggleSwitchSpecifierViewCell` can then use a custom switch which would support custom appearance.  As of UISlider it supports plenty of customization hooks already, so the cell just reconfigures the slider in `-awakeFromNib`.

I’d like to keep the fork as up-to-date with the trunk as possible, so please advise if this mechanism is going to make its way back to trunk, are there any changes or further enhancements that are required or nice to have.

Thanks!

**Comment by futuretap** [comment]
A lot has changed since 2011. IASK 3.0 supports a huge number of customization options. If you're missing anything in particular, please open a new issue.
