### ISSUE TITLE
IASKButtonSpecifier not call

### ISSUE THREAD

**Issue by Arumik** [futuretap/InAppSettingsKit#82]
The button never get called...  am i missing anything?

Root.inApp.plist
Key : TestInBox
Title : Test Button
Type : IASKButtonSpecifier
# import "IASKSpecifier.h"
# import "IASKSettingsReader.h"
- (void)settingsViewController:(IASKAppSettingsViewController_)sender buttonTappedForKey:(NSString_)key {
  if ([key isEqualToString:@"TestInBox"]) { 
      NSLog(@"button worked");
  } 
  }

**Comment by federicocappelli** [comment]
I had the same proplem, for reference:
If you use Storyboard and you create a view controller subclassing IASKAppSettingsViewController you need to set explicitly the delegate with

`self.delegate = self` (or whatever delegate you want)

```
class SettingsViewController: IASKAppSettingsViewController, IASKSettingsDelegate {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.delegate = self
    }
    
    func settingsViewControllerDidEnd(_ sender: IASKAppSettingsViewController!) {
        
    }
    
    func settingsViewController(_ sender: IASKAppSettingsViewController!, buttonTappedFor specifier: IASKSpecifier!) {
        
    }
}
```
